spring.application.name=SangDaeng-001-SQLBank

server.port=8080

#mysql set
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_USERNAME}
spring.datasource.password=${SPRING_USERPW}

mybatis.mapper-locations=classpath*:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

jwt.secret=tkdrneodrncjtvmfhwprxmdla!enendhflWkddlfkdy!rkxmahsqmfforrkxmahsdnwkfdjdnffladjWjfxlqlwjWJfxlqlwjWjfsodwkdrh
jwt.expiration=3600000
#??????????!????????!????????????????????????????



