spring.application.name=SangDaeng-001-SQLBank

server.port=8080

#mysql set
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_USERNAME}
spring.datasource.password=${SPRING_USERPW}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=tkdrneodrncjtvmfhwprxmdla!enendhflWkddlfkdy!rkxmahsqmfforrkxmahsdnwkfdjdnffladjWjfxlqlwjWJfxlqlwjWjfsodwkdrh
jwt.expiration=3600000



