insert into tbl_users (user_id, username, name, password, email, role, created_at, class_num)
values  (1, '1', '관리자', '$2a$10$aGoWkK3b40tmVIgNQqbX6.i5X6NyJVw45FiEsxyjmzHBzLJ8qXPvS', '1', 'ROLE_ADMIN', '2025-02-26 16:20:00', null),
        (2, '2', '안혜빈', '$2a$10$aGoWkK3b40tmVIgNQqbX6.i5X6NyJVw45FiEsxyjmzHBzLJ8qXPvS', '2', 'ROLE_ADMIN', '1998-01-15 23:59:59', null),
        (3, '3', '한상인', '$2a$10$aGoWkK3b40tmVIgNQqbX6.i5X6NyJVw45FiEsxyjmzHBzLJ8qXPvS', '3', 'ROLE_ADMIN', '1999-04-01 00:00:00', null);
        
        insert into tbl_problems (problem_id, question, description, difficulty, user_id, created_at, permit_yn)
values  (1, '부서별 평균 급여를 계산하는 SQL을 작성하시오.', '부서별 평균 급여를 구하기 위해 `AVG()` 함수를 사용합니다. 부서 ID를 기준으로 `GROUP BY`를 사용하여 각 부서별 평균 급여를 계산할 수 있습니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (2, '모든 직원의 정보를 조회하는 SQL을 작성하시오.', '`SELECT * FROM employees;` 명령어를 사용하면 테이블의 모든 데이터를 조회할 수 있습니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (3, '전체 직원 수를 조회하는 SQL을 작성하시오.', '`COUNT()` 함수를 사용하면 특정 컬럼을 기준으로 전체 데이터 개수를 구할 수 있습니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (4, '부서 ID가 10인 직원들의 정보를 조회하는 SQL을 작성하시오.', '`WHERE` 절을 사용하여 특정 조건을 만족하는 데이터를 필터링할 수 있습니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (5, '직원들의 이름을 알파벳 순으로 정렬하여 조회하는 SQL을 작성하시오.', '`ORDER BY` 절을 사용하면 특정 컬럼을 기준으로 정렬할 수 있습니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (6, '데이터베이스에서 PRIMARY KEY의 역할로 적절한 것은 무엇인가?', 'PRIMARY KEY는 테이블 내에서 **고유한 값**을 가지며, 한 행(row)을 **유일하게 식별**하는 역할을 합니다. 중복된 값이 들어갈 수 없으며, NULL 값도 허용되지 않습니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (7, 'WHERE 절을 사용할 때 올바른 예제는 무엇인가?', 'WHERE 절은 특정 조건을 만족하는 데이터만 필터링하여 조회할 때 사용됩니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (8, 'INNER JOIN이 수행하는 기능은 무엇인가?', 'INNER JOIN은 두 개 이상의 테이블을 조인할 때, **공통된 값이 있는 행만 반환**하는 방식입니다. 조건을 만족하는 데이터만 결과에 포함됩니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (9, 'ORDER BY 절의 역할은 무엇인가?', 'ORDER BY 절은 특정 컬럼을 기준으로 데이터를 정렬할 때 사용됩니다. `ASC`는 오름차순(기본값), `DESC`는 내림차순 정렬을 의미합니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (10, 'GROUP BY와 함께 사용할 수 있는 함수로 적절한 것은 무엇인가?', 'GROUP BY는 특정 컬럼을 기준으로 데이터를 그룹화할 때 사용되며, 보통 **집계 함수(Aggregate Function)** 와 함께 사용됩니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (11, '기본 키(Primary Key)와 외래 키(Foreign Key)의 차이점으로 올바른 것은?', '기본 키는 **테이블 내에서 각 행을 유일하게 식별하는 역할**을 하며, 외래 키는 **다른 테이블의 기본 키를 참조하는 컬럼**으로, 테이블 간 관계를 설정하는 데 사용됩니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (12, 'UNIQUE 키의 특징으로 적절한 것은?', 'UNIQUE 키는 컬럼 내에서 **중복된 값을 허용하지 않는 제약 조건**입니다. 그러나 **NULL 값은 허용**할 수 있습니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (13, 'SQL에서 테이블 및 컬럼 이름(식별자)으로 사용할 수 없는 것은?', 'SQL에서 테이블이나 컬럼 이름으로 **예약어(Reserved Keywords)** 를 사용하면 오류가 발생할 수 있습니다. 일부 키워드는 큰따옴표(") 또는 백틱(`)으로 감싸면 사용할 수도 있습니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (14, 'SQL에서 AUTO_INCREMENT가 적용될 수 있는 데이터 타입은?', 'AUTO_INCREMENT는 **자동으로 숫자가 증가하는 속성**이며, 일반적으로 정수(INT)형 컬럼에 사용됩니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (15, 'SQL에서 NULL이 의미하는 것은 무엇인가?', 'NULL은 **값이 존재하지 않음을 의미하는 특별한 상태**이며, 0이나 빈 문자열과는 다릅니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (16, 'employees 테이블에서 부서 ID가 3인 직원들의 모든 정보를 조회하는 SQL을 작성하시오.', '부서 ID가 3인 직원들만 필터링하려면 `WHERE` 절을 활용해야 합니다. `SELECT * FROM employees WHERE department_id = 3;`', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (17, 'employees 테이블에서 가장 높은 급여를 받는 직원의 정보를 조회하는 SQL을 작성하시오.', '급여가 가장 높은 직원을 찾으려면 `ORDER BY`와 `LIMIT 1`을 활용할 수 있습니다. `SELECT * FROM employees ORDER BY salary DESC LIMIT 1;`', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (18, '부서 ID가 2인 직원 중 가장 낮은 급여를 받는 직원의 정보를 조회하는 SQL을 작성하시오.', '특정 부서에서 최저 급여를 받는 직원을 찾으려면 `WHERE`과 `ORDER BY`, `LIMIT 1`을 함께 사용할 수 있습니다. `SELECT * FROM employees WHERE department_id = 2 ORDER BY salary ASC LIMIT 1;`', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (19, 'employees 테이블에서 모든 직원의 평균 급여를 조회하는 SQL을 작성하시오.', '평균 급여를 구하려면 `AVG()` 집계 함수를 사용합니다. `SELECT AVG(salary) FROM employees;`', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (20, '각 부서별 직원 수를 계산하고, 직원 수가 5명 이상인 부서를 조회하는 SQL을 작성하시오.', '직원 수를 세려면 `GROUP BY`와 `HAVING`을 함께 사용해야 합니다. `SELECT department_id, COUNT(*) FROM employees GROUP BY department_id HAVING COUNT(*) >= 5;`', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (21, 'PRIMARY KEY의 역할에 대한 설명으로 알맞은 것은?', 'PRIMARY KEY는 테이블에서 각 행을 고유하게 식별하는 역할을 합니다. 또한, NULL 값을 가질 수 없으며 중복이 허용되지 않습니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (22, 'FOREIGN KEY(외래 키)의 역할에 대한 설명으로 알맞은 것은?', 'FOREIGN KEY는 다른 테이블의 PRIMARY KEY를 참조하는 키입니다. 테이블 간의 관계를 정의하고 데이터 무결성을 보장하는 역할을 합니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (23, 'INDEX(인덱스)의 역할로 올바른 것은?', 'INDEX는 데이터 검색 속도를 향상시키는 역할을 합니다. 하지만 무분별하게 사용하면 오히려 성능이 저하될 수 있습니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (24, 'DDL과 DML의 차이로 올바른 것은?', 'DDL(Data Definition Language)은 테이블을 생성/삭제하는 명령어이고, DML(Data Manipulation Language)은 데이터를 삽입/수정/삭제하는 명령어입니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (25, '트랜잭션(Transaction)의 4가지 속성(ACID) 중 하나가 아닌 것은?', 'ACID는 원자성(Atomicity), 일관성(Consistency), 고립성(Isolation), 지속성(Durability)의 약자입니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (26, 'SQL에서 VIEW(뷰)의 역할로 올바른 것은?', 'VIEW는 실제 테이블이 아니라 특정 쿼리 결과를 저장하는 가상의 테이블입니다. 주로 보안, 데이터 일관성 유지, 복잡한 쿼리 단순화를 위해 사용됩니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (27, 'INNER JOIN과 OUTER JOIN의 차이로 올바른 것은?', 'INNER JOIN은 두 테이블 간 공통된 값이 있는 행만 반환하고, OUTER JOIN은 한쪽 테이블에만 존재하는 행도 반환합니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (28, '다음 중 서브쿼리(Subquery)의 올바른 사용법은?', '서브쿼리는 쿼리 내부에 포함된 또 다른 쿼리로, 주로 `WHERE`, `HAVING`, `FROM` 절에서 사용됩니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (29, 'GROUP BY와 HAVING의 차이로 올바른 것은?', 'GROUP BY는 데이터를 그룹화하는 데 사용되며, HAVING은 그룹화된 결과에 대한 조건을 지정하는 데 사용됩니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (30, 'DEFAULT 제약 조건의 역할로 올바른 것은?', 'DEFAULT 제약 조건은 컬럼에 값이 제공되지 않을 때 기본값을 설정하는 역할을 합니다.', 'EASY', 1, '2025-03-19 15:30:32', 'Y'),
        (31, '각 직원의 부서명과 급여를 함께 조회하는 SQL을 작성하시오.', 'employees 테이블과 departments 테이블을 JOIN하여 부서명과 급여를 함께 출력해야 합니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (32, '각 부서에서 급여가 가장 높은 직원의 ID, 급여, 부서명을 가져오시오.', '서브쿼리를 활용하여 각 부서별 최대 급여를 받는 직원을 조회해야 합니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (33, 'ACID 원칙의 각 개념을 올바르게 설명한 것은?', 'ACID 원칙은 트랜잭션의 신뢰성을 보장하는 중요한 개념입니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (34, '각 부서에서 직원 수가 5명 이상인 부서의 부서명을 조회하시오.', 'HAVING 절을 활용하여 특정 조건을 만족하는 그룹만 조회해야 합니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (35, '데이터베이스 정규화(Normalization)의 주요 목표는 무엇인가?', '정규화는 데이터 중복을 줄이고 무결성을 유지하기 위한 중요한 과정입니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (36, '각 부서에서 직원 수가 가장 많은 부서의 부서명을 조회하는 SQL을 작성하시오.', '서브쿼리를 활용하여 직원 수가 가장 많은 부서를 찾고 해당 부서명을 조회해야 합니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (37, '부서명이 "IT"인 직원들의 직원 ID와 이름을 조회하는 SQL을 작성하시오.', 'INNER JOIN과 WHERE 절을 활용하여 특정 부서의 직원 정보를 조회해야 합니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (38, '중복되지 않은 부서명을 조회하는 SQL을 작성하시오.', 'DISTINCT 키워드를 활용하여 부서명을 중복 없이 출력해야 합니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (39, '평균 급여가 5000 이상인 부서의 부서명과 평균 급여를 가져오시오.', 'HAVING 절을 사용하여 특정 기준을 충족하는 그룹을 필터링해야 합니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (40, '현재 근무하는 직원과 퇴사한 직원의 이름을 모두 가져오는 SQL을 작성하시오.', 'UNION을 사용하여 두 개의 서로 다른 데이터를 하나로 합쳐야 합니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (41, '각 직원의 상사 ID 및 상사 이름을 함께 조회하시오.', 'SELF JOIN을 활용하여 같은 테이블 내에서 관계를 설정해야 합니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (42, '트랜잭션을 사용하여 계좌 이체를 실행하는 SQL을 작성하시오.', '트랜잭션과 COMMIT, ROLLBACK을 활용하여 데이터의 일관성을 유지해야 합니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (43, 'UNION과 UNION ALL의 차이점에 대한 설명으로 올바른 것은?', 'UNION과 UNION ALL은 결과를 합치는 기능이 있지만 동작 방식이 다릅니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (44, '각 부서에서 가장 높은 급여를 받는 직원의 ID와 급여를 조회하는 SQL을 작성하시오.', '각 부서에서 최고 급여를 받는 직원 정보를 가져오기 위해 서브쿼리를 활용해야 합니다. WHERE 절에서 비교를 수행하도록 해야 합니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (45, '부모 테이블에서 특정 데이터를 삭제할 때, 자식 테이블에 해당 데이터가 존재하면 삭제되지 않는 이유는 무엇인가?', '외래 키(Foreign Key) 제약 조건이 걸려 있을 경우, 부모 테이블의 데이터를 삭제하려면 자식 테이블의 데이터를 먼저 삭제해야 합니다. 이 문제는 관계형 데이터베이스에서 데이터 무결성을 보장하는 중요한 개념입니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (46, '각 부서별 직원 수를 조회하는 SQL을 작성하시오.', '각 부서에 속한 직원 수를 구하려면 GROUP BY 절을 사용해야 합니다. COUNT 함수를 활용하여 특정 기준에 따라 데이터를 그룹화하여 집계할 수 있습니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (47, '각 부서에 속한 서로 다른 직책(job_title)의 개수를 조회하는 SQL을 작성하시오.', '중복을 제거하고 고유한 값을 세려면 DISTINCT와 COUNT 함수를 함께 사용해야 합니다. 각 부서별로 직책의 개수를 집계하는 방식으로 해결할 수 있습니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (48, '각 학생의 평균 학점을 계산하여, 평균 학점이 3.5 이상인 학생만 조회하는 SQL을 작성하시오.', '학생들의 학점을 저장하는 `grades` 테이블이 있고, 각 학생의 성적 정보를 `student_id`를 기준으로 그룹화해야 합니다. 평균 학점을 계산하기 위해 `AVG()` 함수를 사용하며, 조건을 만족하는 학생만 조회하려면 `HAVING` 절을 활용해야 합니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (49, '가장 많이 주문된 상품(product_id)과 주문 횟수를 조회하는 SQL을 작성하시오.', '고객의 주문 기록을 저장하는 `orders` 테이블이 있으며, 주문된 상품 정보는 `product_id` 컬럼에 저장됩니다. 가장 많이 주문된 상품을 찾으려면 `COUNT()` 함수를 사용하고, `ORDER BY` 절을 활용하여 결과를 정렬해야 합니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (50, '현재 대출 중인 도서 목록을 조회하는 SQL을 작성하시오.', '도서 대출 정보를 저장하는 `library_loans` 테이블이 있으며, 반납 여부를 확인하는 `return_date` 컬럼이 있습니다. 현재 대출 중인 도서를 조회하려면 `return_date`가 `NULL`인 레코드만 선택해야 합니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (51, '2024년 5월에 주문된 주문 목록을 조회하는 SQL을 작성하시오.', '주문 정보를 저장하는 `orders` 테이블이 있으며, 주문 날짜는 `order_date` 컬럼에 저장됩니다. 특정 연도와 월에 해당하는 주문을 조회하려면 `YEAR()`, `MONTH()` 또는 `DATE_FORMAT()` 함수를 활용해야 합니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (52, '학생들의 평균 성적을 저장하는 `student_avg_scores` 뷰를 생성하는 SQL을 작성하시오.', '학생들의 성적 정보는 `grades` 테이블에 있으며, 각 학생의 평균 성적을 저장하는 뷰를 생성해야 합니다. 뷰는 `CREATE VIEW` 문을 사용하여 생성되며, 학생 ID와 평균 점수를 포함해야 합니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (53, '부서별 평균 급여보다 높은 급여를 받는 직원들을 조회하는 SQL을 작성하시오.', '각 부서의 평균 급여를 계산한 후, 해당 평균보다 높은 급여를 받는 직원만 조회해야 합니다. 이를 위해 `HAVING` 절이 아니라 `WHERE` 절과 서브쿼리를 활용해야 합니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (54, '상품의 가격을 기준으로 등급을 나누어 조회하는 SQL을 작성하시오.', '상품 테이블(`products`)에서 가격(price)이 50000원 이상이면 "고가", 20000원 이상이면 "중가", 그렇지 않으면 "저가"로 분류하여 조회해야 합니다. `CASE` 문을 활용하여 각 상품의 등급을 표시하세요.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (55, '신규 고객과 기존 고객을 구분하여 조회하는 SQL을 작성하시오.', '`customers` 테이블에는 고객 ID와 가입일(`join_date`) 정보가 있습니다. 2023년 이후 가입한 고객을 "신규 고객", 그 이전 가입한 고객을 "기존 고객"으로 분류하여 조회하세요. `UNION`을 사용하여 두 개의 쿼리 결과를 하나로 합쳐야 합니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (56, '주문 테이블에서 특정 주문을 취소할 때 트랜잭션을 활용하는 SQL을 작성하시오.', '트랜잭션을 사용하여 `orders` 테이블에서 주문을 취소(`status`를 "CANCELLED"로 변경)하고, 동시에 결제(`payments`) 정보를 삭제하는 SQL을 작성하세요. 오류가 발생하면 전체 작업이 롤백되어야 합니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (57, '각 직원이 속한 부서에서 연봉 순위를 매기는 SQL을 작성하시오.', '`employees` 테이블에서 직원의 ID, 이름, 부서 ID, 연봉 정보를 가져온 후, 같은 부서 내에서 연봉 순위를 매겨 "연봉 순위"를 추가해야 합니다.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (58, '각 직원의 상사 이름을 함께 조회하는 SQL을 작성하시오.', '`employees` 테이블에서 직원의 ID, 이름과 함께 해당 직원의 상사(manager)의 이름을 가져와야 합니다. SELF JOIN을 활용하여 상사-직원 관계를 표현하세요.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (59, '직원 이메일 주소에서 도메인 부분만 추출하는 SQL을 작성하시오.', '`employees` 테이블에는 `email` 컬럼이 있습니다. 이메일 주소에서 "@" 뒤의 도메인만 추출하여 조회하세요.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (60, '부서별 직원 이름을 하나의 문자열로 묶어 조회하는 SQL을 작성하시오.', '`employees` 테이블에서 같은 부서에 속한 직원들의 이름을 쉼표(,)로 구분하여 하나의 문자열로 묶어야 합니다. `GROUP_CONCAT()` 함수를 활용하세요.', 'MEDIUM', 1, '2025-03-19 15:30:33', 'Y'),
        (61, '각 반에서 최고 성적을 받은 학생의 ID, 이름, 점수를 조회하는 SQL을 작성하시오.', '서브쿼리를 활용하여 반별 최고 성적을 가진 학생을 찾는 방법을 묻는 문제입니다. 
  반별 최고 성적을 찾기 위해 서브쿼리를 사용하거나 RANK() 같은 윈도우 함수를 활용할 수도 있습니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (62, '특정 직원(employee_id = 5)의 모든 부하 직원을 조회하는 SQL을 작성하시오.', '이 문제는 재귀적 CTE(Common Table Expression, WITH RECURSIVE)를 활용하여 계층 구조를 탐색하는 문제입니다.
  부서 구조나 조직도를 표현할 때 자주 사용됩니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (63, '대용량 sales 테이블에서 월별 총 매출을 빠르게 조회하는 SQL을 작성하시오.', '이 문제는 파티션 테이블(Partition Table)을 활용하여 대용량 데이터의 성능을 최적화하는 방법을 묻습니다.
  월별 데이터를 파티셔닝한 상태에서 특정 월의 매출을 조회하는 SQL을 작성해야 합니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (64, '최근 3개월 동안의 평균 매출을 조회하는 SQL을 작성하시오.', '윈도우 함수 AVG()를 활용하여 최근 3개월 동안 평균적으로 발생한 매출을 계산하는 문제입니다. 
  LAG(), LEAD(), PARTITION BY 등을 적절히 활용해야 합니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (65, '지난 한 달 동안 가장 많이 판매된 상품을 조회하는 SQL을 작성하시오.', '서브쿼리를 활용하여 가장 많이 팔린 상품을 찾는 방법을 묻는 문제입니다. 
  RANK() 윈도우 함수를 활용하는 방식과 MAX()를 활용하는 방식이 있습니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (66, '고객 ID가 1001인 고객의 총 주문 금액을 조회하는 SQL을 작성하시오.', 'SUM()과 GROUP BY를 활용하여 특정 고객이 지금까지 주문한 총 금액을 계산하는 문제입니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (67, '카테고리 테이블에서 특정 카테고리의 모든 하위 카테고리를 조회하는 SQL을 작성하시오.', '재귀적 CTE (WITH RECURSIVE)를 활용하여 계층 구조를 탐색하는 문제입니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (68, '대용량 로그 테이블에서 특정 날짜의 사용자 활동 로그를 빠르게 조회하는 SQL을 작성하시오.', '파티션 테이블을 활용하여 특정 날짜에 대한 사용자 로그를 조회하는 문제입니다. 
  WHERE 절과 PARTITION을 조합해야 합니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (69, '최근 3개월 동안 각 고객의 매출 증가율을 계산하는 SQL을 작성하시오.', 'PARTITION BY와 LAG() 함수를 활용하여 각 고객의 매출이 전월 대비 얼마나 증가했는지 분석하는 문제입니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (70, '카테고리별, 브랜드별, 전체 매출을 한 번의 쿼리로 조회하는 SQL을 작성하시오.', 'GROUPING SETS를 사용하여 다양한 수준의 집계 데이터를 동시에 구하는 문제입니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (71, '단 한 번도 주문을 하지 않은 고객 목록을 조회하는 SQL을 작성하시오.', 'NOT EXISTS를 사용하여 주문 테이블에 존재하지 않는 고객을 찾는 문제입니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (72, '각 부서별 직원의 연봉 순위를 계산하는 SQL을 작성하시오.', 'PARTITION BY와 RANK()를 활용하여 부서별 연봉 순위를 매기는 문제입니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (73, '월별 매출과 전체 매출을 한 번의 쿼리로 조회하는 SQL을 작성하시오.', 'GROUPING SETS를 활용하여 월별 총 매출과 전체 매출을 동시에 출력하는 문제입니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (74, '각 부서에서 가장 최근에 입사한 직원의 정보를 조회하는 SQL을 작성하시오.', 'PARTITION BY와 FIRST_VALUE() 함수를 사용하여 부서별로 가장 최근에 입사한 직원을 찾는 문제입니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (75, '카테고리별, 브랜드별, 전체 판매량을 한 번의 쿼리로 조회하는 SQL을 작성하시오.', 'GROUPING SETS를 활용하여 다양한 수준의 판매량 집계를 동시에 조회하는 문제입니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (76, '특정 제품(Product A)을 한 번도 구매하지 않은 고객 목록을 조회하는 SQL을 작성하시오.', 'NOT EXISTS를 사용하여 특정 제품을 구매한 적이 없는 고객을 찾는 문제입니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (77, '학생별 최근 3회 시험 성적의 평균을 계산하는 SQL을 작성하시오.', 'PARTITION BY와 ROW_NUMBER()를 사용하여 최근 3회의 성적을 기준으로 평균을 구하는 문제입니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (78, 'GROUPING SETS란 무엇이며, ROLLUP 및 CUBE와의 차이점은 무엇인가?', 'GROUPING SETS는 다중 집계 수준을 한 번의 쿼리에서 수행할 수 있도록 하는 기능입니다. ROLLUP은 계층적 집계를 수행하고, CUBE는 가능한 모든 조합에 대해 집계를 수행하는 반면, GROUPING SETS는 특정한 집계 조합을 명시적으로 지정할 수 있습니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (79, '윈도우 함수와 일반 집계 함수의 차이점은 무엇인가?', '윈도우 함수는 OVER() 절을 사용하여 집계 결과를 개별 행에 유지하면서 수행할 수 있으며, 기존 행 데이터를 보존합니다. 반면, 일반 집계 함수는 여러 행을 하나의 결과로 축약합니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (80, 'NOT EXISTS와 LEFT JOIN을 활용한 필터링은 어떤 차이가 있는가?', 'NOT EXISTS는 서브쿼리에서 특정 조건을 만족하는 데이터가 존재하지 않는 경우를 필터링하는 반면, LEFT JOIN과 WHERE NULL을 사용하면 특정 테이블에 대응하는 데이터가 없는 경우를 찾을 수 있습니다. 하지만 LEFT JOIN은 불필요한 중복 데이터를 초래할 수 있어 성능에 영향을 줄 수 있습니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (81, 'PARTITION BY와 GROUP BY의 차이점은 무엇인가?', 'GROUP BY는 특정 컬럼을 기준으로 데이터를 그룹화하여 집계 값을 반환하는 반면, PARTITION BY는 윈도우 함수를 사용하여 개별 행을 보존하면서 그룹 내에서 연산을 수행할 수 있도록 합니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (82, '가장 많은 주문을 한 고객의 ID와 총 주문 횟수를 조회하는 SQL을 작성하시오.', '이 문제를 해결하려면 `COUNT(*)`를 사용하여 고객별 주문 횟수를 계산한 후, 서브쿼리를 사용하여 주문 횟수가 가장 높은 고객을 필터링해야 합니다. 즉, 주문 테이블에서 고객별 주문 횟수를 구한 뒤, 그 중 최대값을 찾고 해당 값을 가진 고객을 조회하면 됩니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (83, '각 직원의 급여가 해당 부서의 평균 급여보다 높은 직원의 ID, 이름, 급여를 조회하는 SQL을 작성하시오.', '각 직원의 급여가 속한 부서의 평균 급여보다 높은지 판단하려면 상관 서브쿼리를 사용해야 합니다. 즉, 메인 쿼리에서 개별 직원 데이터를 조회하고, 서브쿼리에서 해당 직원이 속한 부서의 평균 급여를 계산하여 비교하면 됩니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (84, '최근 3개월 동안 가장 많이 판매된 상품의 ID, 이름, 총 판매량을 조회하는 SQL을 작성하시오.', '이 문제를 해결하려면 먼저 주문 날짜를 기준으로 최근 3개월 데이터를 필터링한 후, 상품별 판매량을 계산해야 합니다. 그 다음, 서브쿼리를 사용하여 최대 판매량을 찾고 해당 값을 가진 상품을 조회하면 됩니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (85, '고객별 총 구매 금액을 계산하고, 특정 조건을 충족하는 고객에게 등급을 부여하는 SQL을 작성하시오.', '이 문제를 해결하려면 `SUM(order_amount)`을 사용하여 고객별 총 구매 금액을 계산한 후, 서브쿼리를 사용하여 각 고객의 총 구매 금액을 기반으로 등급을 부여해야 합니다. 예를 들어, 1000달러 이상 구매한 고객은 "VIP"로 분류하고, 500~999달러 구매한 고객은 "PREMIUM"으로, 그 이하는 "REGULAR"로 분류할 수 있습니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (86, '각 제품의 카테고리별 총 매출, 그리고 전체 총 매출을 동시에 조회하는 SQL을 작성하시오.', 'GROUPING SETS를 활용하면 단일 쿼리에서 여러 가지 집계 결과를 동시에 얻을 수 있습니다. 이 문제에서는 특정 그룹별 총 매출뿐만 아니라 전체 총 매출도 함께 계산해야 하므로, GROUP BY와 함께 GROUPING SETS를 적절히 사용해야 합니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (87, '한 번도 주문하지 않은 고객의 ID와 이름을 조회하는 SQL을 작성하시오.', 'NOT EXISTS는 특정 조건을 만족하지 않는 데이터를 찾을 때 유용하게 사용됩니다. 이 문제에서는 `customers` 테이블에 존재하지만, `orders` 테이블에 등장하지 않은 고객을 조회해야 합니다. 즉, 주문 정보가 없는 고객을 찾는 것이므로 NOT EXISTS 또는 LEFT JOIN과 NULL 체크를 활용할 수 있습니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (88, '각 직원이 속한 부서 내에서 자신의 급여 순위를 조회하는 SQL을 작성하시오.', '이 문제에서는 같은 부서 내에서 직원들의 급여 순위를 매겨야 하므로, RANK() 또는 DENSE_RANK()를 PARTITION BY와 함께 사용해야 합니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (89, '고객들이 한 번도 주문한 적이 없는 제품의 ID, 이름을 조회하는 SQL을 작성하시오.', '이 문제에서는 특정 제품이 주문된 적이 없는지 확인해야 하므로, NOT EXISTS를 활용하여 주문 테이블에 해당 제품이 존재하는지 체크해야 합니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y'),
        (90, '각 고객의 월별 총 구매 금액, 연도별 총 구매 금액을 동시에 조회하는 SQL을 작성하시오.', '이 문제에서는 GROUPING SETS를 사용하여 월별, 연도별 집계를 동시에 조회해야 합니다. 또한, PARTITION BY를 활용하면 개별 고객이 특정 월과 연도에서 구매한 총 금액을 구할 수 있습니다.', 'HARD', 1, '2025-03-19 15:30:38', 'Y');
        
        insert into tbl_problem_choices (choice_id, problem_id, choice_text, is_correct)
values  (1, 1, 'SELECT department_id, SUM(salary) FROM employees GROUP BY department_id;', 0),
        (2, 1, 'SELECT department_id, COUNT(salary) FROM employees GROUP BY department_id;', 0),
        (3, 1, 'SELECT department_id, AVG(salary) FROM employees GROUP BY department_id;', 1),
        (4, 1, 'SELECT department_id, MIN(salary) FROM employees;', 0),
        (5, 1, 'SELECT department_id, MAX(salary) FROM employees GROUP BY department_id;', 0),
        (6, 1, 'SELECT department_id, salary FROM employees ORDER BY salary DESC;', 0),
        (7, 1, 'SELECT department_id, salary FROM employees WHERE salary > 5000;', 0),
        (8, 1, 'SELECT AVG(salary) FROM employees;', 0),
        (9, 2, 'SELECT employee_id, name FROM employees;', 0),
        (10, 2, 'SELECT * FROM employees;', 1),
        (11, 2, 'SELECT name FROM employees WHERE employee_id = 1;', 0),
        (12, 2, 'SELECT name, salary FROM employees;', 0),
        (13, 2, 'SELECT department_id FROM employees;', 0),
        (14, 2, 'SELECT COUNT(*) FROM employees;', 0),
        (15, 2, 'SELECT DISTINCT department_id FROM employees;', 0),
        (16, 2, 'SELECT SUM(salary) FROM employees;', 0),
        (17, 3, 'SELECT * FROM employees;', 0),
        (18, 3, 'SELECT COUNT(*) FROM employees;', 1),
        (19, 3, 'SELECT COUNT(salary) FROM employees;', 0),
        (20, 3, 'SELECT employee_id FROM employees;', 0),
        (21, 3, 'SELECT DISTINCT name FROM employees;', 0),
        (22, 3, 'SELECT MIN(salary) FROM employees;', 0),
        (23, 3, 'SELECT AVG(salary) FROM employees;', 0),
        (24, 3, 'SELECT MAX(employee_id) FROM employees;', 0),
        (25, 4, 'SELECT * FROM employees WHERE salary > 5000;', 0),
        (26, 4, 'SELECT * FROM employees WHERE department_id = 10;', 1),
        (27, 4, 'SELECT * FROM employees WHERE name LIKE "김%";', 0),
        (28, 4, 'SELECT name FROM employees WHERE department_id > 10;', 0),
        (29, 4, 'SELECT department_id FROM employees;', 0),
        (30, 4, 'SELECT employee_id, name FROM employees;', 0),
        (31, 4, 'SELECT DISTINCT department_id FROM employees;', 0),
        (32, 4, 'SELECT COUNT(*) FROM employees WHERE department_id = 10;', 0),
        (33, 5, 'SELECT * FROM employees ORDER BY salary;', 0),
        (34, 5, 'SELECT name FROM employees ORDER BY name;', 1),
        (35, 5, 'SELECT * FROM employees ORDER BY department_id;', 0),
        (36, 5, 'SELECT employee_id FROM employees ORDER BY name;', 0),
        (37, 5, 'SELECT name, salary FROM employees ORDER BY salary DESC;', 0),
        (38, 5, 'SELECT department_id FROM employees ORDER BY employee_id;', 0),
        (39, 5, 'SELECT * FROM employees WHERE name LIKE "A%";', 0),
        (40, 5, 'SELECT COUNT(*) FROM employees ORDER BY name;', 0),
        (41, 6, '중복된 값을 허용한다.', 0),
        (42, 6, 'NULL 값을 허용할 수 있다.', 0),
        (43, 6, '한 테이블에서 여러 개의 PRIMARY KEY를 설정할 수 있다.', 0),
        (44, 6, '각 행을 유일하게 식별한다.', 1),
        (45, 6, '데이터 정렬을 위한 속성이다.', 0),
        (46, 6, '테이블 간 관계를 설정하는 데 사용된다.', 0),
        (47, 6, '쿼리 속도를 빠르게 하기 위한 용도로만 사용된다.', 0),
        (48, 6, '삭제할 수 없는 필드이다.', 0),
        (49, 7, 'SELECT * FROM employees;', 0),
        (50, 7, 'SELECT * FROM employees WHERE department_id = 10;', 1),
        (51, 7, 'SELECT department_id FROM employees GROUP BY department_id;', 0),
        (52, 7, 'SELECT COUNT(*) FROM employees;', 0),
        (53, 7, 'SELECT name FROM employees ORDER BY name;', 0),
        (54, 7, 'SELECT DISTINCT department_id FROM employees;', 0),
        (55, 7, 'SELECT * FROM employees WHERE salary;', 0),
        (56, 7, 'SELECT MAX(salary) FROM employees WHERE name;', 0),
        (57, 8, '모든 데이터를 포함하여 조인한다.', 0),
        (58, 8, '조건이 일치하는 행만 반환한다.', 1),
        (59, 8, '왼쪽 테이블의 모든 행을 반환한다.', 0),
        (60, 8, '오른쪽 테이블의 모든 행을 반환한다.', 0),
        (61, 8, '조인된 테이블의 모든 행을 합친다.', 0),
        (62, 8, 'GROUP BY와 함께 사용할 수 없다.', 0),
        (63, 8, '조건이 없어도 자동으로 조인된다.', 0),
        (64, 8, '조인할 수 있는 컬럼 개수가 제한된다.', 0),
        (65, 9, '데이터를 그룹화한다.', 0),
        (66, 9, '데이터를 정렬한다.', 1),
        (67, 9, '쿼리 실행 속도를 높인다.', 0),
        (68, 9, '테이블 간 관계를 설정한다.', 0),
        (69, 9, '중복 데이터를 제거한다.', 0),
        (70, 9, '데이터를 삽입하는 데 사용된다.', 0),
        (71, 9, '조건을 추가하는 역할을 한다.', 0),
        (72, 9, '특정 컬럼을 삭제하는 역할을 한다.', 0),
        (73, 10, 'SUM()', 1),
        (77, 10, 'ORDER BY', 0),
        (78, 10, 'INSERT INTO', 0),
        (79, 10, 'DELETE', 0),
        (80, 10, 'DROP TABLE', 0),
        (81, 11, '기본 키는 중복 가능하지만, 외래 키는 중복 불가능하다.', 0),
        (82, 11, '기본 키는 한 테이블에 여러 개 설정할 수 있다.', 0),
        (83, 11, '외래 키는 기본 키를 참조하여 테이블 간 관계를 설정한다.', 1),
        (84, 11, '외래 키는 NULL 값을 가질 수 없다.', 0),
        (85, 11, '기본 키는 자동 증가하는 값만 사용할 수 있다.', 0),
        (86, 11, '외래 키는 하나의 테이블에서만 사용 가능하다.', 0),
        (87, 11, '기본 키는 다른 테이블의 기본 키를 참조한다.', 0),
        (88, 11, '기본 키는 무조건 숫자로만 구성되어야 한다.', 0),
        (89, 12, 'NULL 값을 가질 수 없다.', 0),
        (90, 12, '한 테이블에 UNIQUE 키를 여러 개 설정할 수 없다.', 0),
        (91, 12, '각 행의 값을 고유하게 유지해야 한다.', 1),
        (92, 12, '기본 키와 같은 역할을 한다.', 0),
        (93, 12, '데이터 정렬을 담당하는 키이다.', 0),
        (94, 12, '외래 키와 반드시 함께 사용해야 한다.', 0),
        (95, 12, 'UNIQUE 키는 테이블을 삭제하면 자동으로 제거된다.', 0),
        (96, 12, '모든 테이블에 반드시 포함되어야 한다.', 0),
        (97, 13, 'user', 0),
        (98, 13, 'order', 0),
        (99, 13, 'select', 1),
        (100, 13, 'table_name', 0),
        (101, 13, 'customer_data', 0),
        (102, 13, 'my_column', 0),
        (104, 13, 'employee', 0),
        (105, 14, 'VARCHAR', 0),
        (106, 14, 'TEXT', 0),
        (107, 14, 'FLOAT', 0),
        (108, 14, 'BOOLEAN', 0),
        (109, 14, 'INT', 1),
        (110, 14, 'DATE', 0),
        (111, 14, 'DECIMAL', 0),
        (112, 14, 'CHAR', 0),
        (113, 15, '0과 동일한 값이다.', 0),
        (114, 15, '빈 문자열과 동일하다.', 0),
        (115, 15, '값이 존재하지 않음을 의미한다.', 1),
        (116, 15, 'NULL 값을 비교할 때는 "=" 연산자를 사용한다.', 0),
        (117, 15, 'NULL 값을 가진 컬럼은 정렬에서 제외된다.', 0),
        (118, 15, 'NULL 값은 반드시 변경해야 한다.', 0),
        (119, 15, 'NULL 값이 있는 경우 해당 행은 자동 삭제된다.', 0),
        (120, 15, 'NULL 값은 기본적으로 0으로 변환된다.', 0),
        (121, 16, 'SELECT * FROM employees;', 0),
        (122, 16, 'SELECT department_id FROM employees WHERE department_id = 3;', 0),
        (123, 16, 'SELECT * FROM employees WHERE department_id = 3;', 1),
        (124, 16, 'SELECT name FROM employees WHERE department_id = 3;', 0),
        (125, 16, 'SELECT * FROM employees WHERE employee_id = 3;', 0),
        (126, 16, 'SELECT * FROM departments WHERE department_id = 3;', 0),
        (127, 16, 'SELECT * FROM employees WHERE salary > 3;', 0),
        (128, 16, 'SELECT * FROM employees ORDER BY department_id;', 0),
        (129, 17, 'SELECT salary FROM employees;', 0),
        (130, 17, 'SELECT * FROM employees WHERE salary = MAX(salary);', 0),
        (131, 17, 'SELECT * FROM employees ORDER BY salary ASC LIMIT 1;', 0),
        (132, 17, 'SELECT * FROM employees ORDER BY salary DESC LIMIT 1;', 1),
        (133, 17, 'SELECT name, salary FROM employees ORDER BY salary DESC;', 0),
        (134, 17, 'SELECT * FROM employees WHERE salary > 100000;', 0),
        (135, 17, 'SELECT * FROM employees WHERE department_id = (SELECT department_id FROM employees ORDER BY salary DESC LIMIT 1);', 0),
        (136, 17, 'SELECT employee_id, name FROM employees ORDER BY salary DESC;', 0),
        (137, 18, 'SELECT * FROM employees WHERE salary = MIN(salary) AND department_id = 2;', 0),
        (138, 18, 'SELECT * FROM employees WHERE department_id = 2 ORDER BY salary ASC LIMIT 1;', 1),
        (139, 18, 'SELECT * FROM employees ORDER BY salary ASC LIMIT 1;', 0),
        (140, 18, 'SELECT * FROM employees WHERE department_id = 2 AND salary < AVG(salary);', 0),
        (141, 18, 'SELECT employee_id FROM employees WHERE department_id = 2 ORDER BY salary DESC;', 0),
        (142, 18, 'SELECT department_id FROM employees WHERE salary = MIN(salary);', 0),
        (143, 18, 'SELECT * FROM employees WHERE department_id = 2 AND salary = MAX(salary);', 0),
        (145, 19, 'SELECT salary FROM employees;', 0),
        (146, 19, 'SELECT SUM(salary) FROM employees;', 0),
        (147, 19, 'SELECT COUNT(salary) FROM employees;', 0),
        (148, 19, 'SELECT AVG(salary) FROM employees;', 1),
        (149, 19, 'SELECT MAX(salary) FROM employees;', 0),
        (150, 19, 'SELECT MIN(salary) FROM employees;', 0),
        (151, 19, 'SELECT * FROM employees ORDER BY salary;', 0),
        (152, 19, 'SELECT AVG(salary) FROM employees WHERE department_id = 1;', 0),
        (153, 20, 'SELECT * FROM employees WHERE COUNT(*) >= 5;', 0),
        (154, 20, 'SELECT department_id, COUNT(*) FROM employees GROUP BY department_id;', 0),
        (155, 20, 'SELECT department_id, COUNT(*) FROM employees GROUP BY department_id HAVING COUNT(*) >= 5;', 1),
        (156, 20, 'SELECT department_id FROM employees WHERE COUNT(*) > 5;', 0),
        (157, 20, 'SELECT * FROM employees GROUP BY department_id;', 0),
        (158, 20, 'SELECT department_id FROM employees ORDER BY COUNT(*) DESC;', 0),
        (159, 20, 'SELECT department_id FROM employees GROUP BY department_id HAVING COUNT(*) < 5;', 0),
        (160, 20, 'SELECT COUNT(*) FROM employees GROUP BY department_id;', 0),
        (161, 21, '테이블의 모든 컬럼을 기본 키로 설정하는 것', 0),
        (162, 21, '중복 값을 허용하는 제약 조건', 0),
        (163, 21, 'NULL 값을 가질 수 있는 제약 조건', 0),
        (164, 21, '테이블에서 각 행을 고유하게 식별하는 키', 1),
        (165, 21, '인덱스와 동일한 기능을 수행하는 키', 0),
        (166, 21, '외래 키와 동일한 기능을 수행하는 키', 0),
        (167, 21, '한 테이블에 여러 개를 가질 수 있는 키', 0),
        (168, 21, '제약 조건이 없는 키', 0),
        (169, 22, '테이블에서 각 행을 고유하게 식별하는 키', 0),
        (170, 22, '한 테이블 내에서만 사용되는 키', 0),
        (171, 22, '다른 테이블의 PRIMARY KEY를 참조하는 키', 1),
        (172, 22, 'NULL 값을 가질 수 없는 키', 0),
        (173, 22, '자동으로 증가하는 키', 0),
        (174, 22, '테이블의 모든 컬럼을 포함하는 키', 0),
        (175, 22, '데이터를 중복 저장하는 키', 0),
        (176, 22, '테이블을 삭제할 수 없도록 하는 키', 0),
        (177, 23, '테이블 데이터를 자동으로 정렬하는 기능', 0),
        (178, 23, '데이터 검색 속도를 향상시키는 기능', 1),
        (179, 23, '자동 증가(AUTO_INCREMENT) 값을 관리하는 기능', 0),
        (180, 23, '모든 테이블에 자동으로 생성되는 기능', 0),
        (181, 23, '테이블의 모든 데이터를 압축하는 기능', 0),
        (182, 23, '데이터를 삭제할 수 없도록 보호하는 기능', 0),
        (183, 23, '트랜잭션을 자동으로 롤백하는 기능', 0),
        (184, 23, 'FOREIGN KEY의 역할과 동일한 기능', 0),
        (185, 24, 'DDL은 데이터를 조작하는 명령어이고, DML은 테이블을 생성하는 명령어이다.', 0),
        (186, 24, 'DDL은 테이블을 생성/삭제하는 명령어이고, DML은 데이터를 조작하는 명령어이다.', 1),
        (187, 24, 'DDL과 DML은 동일한 기능을 수행한다.', 0),
        (188, 24, 'DDL은 SELECT 문을 포함하고 있다.', 0),
        (189, 24, 'DML은 테이블의 구조를 변경하는 명령어이다.', 0),
        (190, 24, 'DDL은 데이터를 삭제하는 명령어이다.', 0),
        (191, 24, 'DDL과 DML 모두 데이터를 삽입하는 기능을 수행한다.', 0),
        (192, 24, 'DDL은 트랜잭션을 관리하는 명령어이다.', 0),
        (193, 25, 'Atomicity (원자성)', 0),
        (194, 25, 'Consistency (일관성)', 0),
        (195, 25, 'Isolation (고립성)', 0),
        (196, 25, 'Durability (지속성)', 0),
        (197, 25, 'Integrity (무결성)', 1),
        (198, 25, 'Performance (성능)', 0),
        (199, 25, 'Efficiency (효율성)', 0),
        (200, 25, 'Recovery (복구)', 0),
        (201, 26, 'VIEW는 데이터를 물리적으로 저장하는 테이블이다.', 0),
        (202, 26, 'VIEW는 특정 쿼리 결과를 저장하는 가상의 테이블이다.', 1),
        (203, 26, 'VIEW는 PRIMARY KEY를 자동으로 생성한다.', 0),
        (204, 26, 'VIEW는 데이터 삽입만 가능하며 조회는 불가능하다.', 0),
        (205, 26, 'VIEW는 트랜잭션을 관리하는 기능이 있다.', 0),
        (206, 26, 'VIEW는 테이블을 삭제하는 기능이다.', 0),
        (207, 26, 'VIEW는 인덱스를 자동으로 생성하는 기능이 있다.', 0),
        (208, 26, 'VIEW는 테이블의 모든 데이터를 무조건 포함해야 한다.', 0),
        (209, 27, 'INNER JOIN은 모든 데이터를 반환하고, OUTER JOIN은 일부 데이터를 반환한다.', 0),
        (210, 27, 'INNER JOIN은 두 테이블 간 공통된 값이 있는 행만 반환한다.', 1),
        (211, 27, 'OUTER JOIN은 공통된 값이 있는 데이터만 조회한다.', 0),
        (212, 27, 'INNER JOIN과 OUTER JOIN은 동일한 결과를 반환한다.', 0),
        (213, 27, 'INNER JOIN은 NULL 값을 반환할 수 있다.', 0),
        (215, 27, 'OUTER JOIN은 데이터 정렬을 자동으로 수행한다.', 0),
        (216, 27, 'INNER JOIN은 다른 테이블의 데이터를 변경할 수 있다.', 0),
        (217, 28, '서브쿼리는 WHERE 절에서만 사용할 수 있다.', 0),
        (218, 28, '서브쿼리는 하나의 쿼리 안에 포함된 또 다른 쿼리이다.', 1),
        (219, 28, '서브쿼리는 반드시 SELECT 문만 사용할 수 있다.', 0),
        (220, 28, '서브쿼리는 FROM 절에서는 사용할 수 없다.', 0),
        (222, 28, '서브쿼리는 무조건 JOIN보다 성능이 뛰어나다.', 0),
        (223, 28, '서브쿼리는 항상 단일 행 결과만 반환해야 한다.', 0),
        (224, 28, '서브쿼리는 트랜잭션을 자동으로 관리한다.', 0),
        (225, 29, 'GROUP BY는 데이터를 그룹화하고, HAVING은 그룹화된 결과에 대한 조건을 지정한다.', 1),
        (226, 29, 'GROUP BY는 데이터를 정렬하는 기능을 한다.', 0),
        (227, 29, 'HAVING은 테이블을 생성하는 기능이 있다.', 0),
        (228, 29, 'GROUP BY는 SELECT 절에서만 사용할 수 있다.', 0),
        (229, 29, 'HAVING은 WHERE 절과 동일한 역할을 한다.', 0),
        (230, 29, 'GROUP BY는 NULL 값을 제거하는 기능이 있다.', 0),
        (231, 29, 'HAVING은 오직 SUM 함수에서만 사용 가능하다.', 0),
        (232, 29, 'GROUP BY는 데이터 삽입 시 자동으로 적용된다.', 0),
        (233, 30, 'DEFAULT 제약 조건은 데이터베이스의 모든 테이블에 자동으로 설정된다.', 0),
        (234, 30, 'DEFAULT 제약 조건은 NULL 값을 허용하지 않는 제약 조건이다.', 0),
        (235, 30, 'DEFAULT 제약 조건은 컬럼에 값이 제공되지 않을 때 기본값을 설정한다.', 1),
        (236, 30, 'DEFAULT 제약 조건은 PRIMARY KEY와 동일한 기능을 한다.', 0),
        (237, 30, 'DEFAULT 제약 조건은 UPDATE 문에서만 사용된다.', 0),
        (238, 30, 'DEFAULT 제약 조건은 다른 테이블을 참조하는 키이다.', 0),
        (239, 30, 'DEFAULT 제약 조건은 트랜잭션을 자동으로 관리한다.', 0),
        (240, 30, 'DEFAULT 제약 조건은 AUTO_INCREMENT와 동일한 기능을 한다.', 0),
        (241, 31, 'SELECT e.name, d.department_name, e.salary FROM employees e JOIN departments d ON e.department_id = d.department_id;', 1),
        (242, 31, 'SELECT name, department_name, salary FROM employees NATURAL JOIN departments;', 0),
        (243, 31, 'SELECT e.name, d.name, e.salary FROM employees e LEFT JOIN departments d ON e.department_id = d.department_id;', 0),
        (244, 31, 'SELECT e.name, d.department_name FROM employees e INNER JOIN departments d ON e.department_id = d.department_id;', 0),
        (245, 31, 'SELECT e.name, d.department_name FROM employees e FULL OUTER JOIN departments d ON e.department_id = d.department_id;', 0),
        (246, 31, 'SELECT name, department_name, salary FROM employees, departments WHERE employees.department_id = departments.department_id;', 0),
        (247, 31, 'SELECT e.name, d.department_name, SUM(e.salary) FROM employees e LEFT JOIN departments d ON e.department_id = d.department_id;', 0),
        (248, 31, 'SELECT e.name, e.salary FROM employees e WHERE EXISTS (SELECT * FROM departments d WHERE e.department_id = d.department_id);', 0),
        (249, 32, 'SELECT e.employee_id, e.salary, d.department_name FROM employees e JOIN departments d ON e.department_id = d.department_id WHERE e.salary = (SELECT MAX(salary) FROM employees WHERE department_id = e.department_id);', 1),
        (250, 32, 'SELECT e.employee_id, e.salary, d.department_name FROM employees e JOIN departments d ON e.department_id = d.department_id GROUP BY d.department_name;', 0),
        (251, 32, 'SELECT e.employee_id, e.salary, d.department_name FROM employees e LEFT JOIN departments d ON e.department_id = d.department_id;', 0),
        (252, 32, 'SELECT e.employee_id, e.salary FROM employees e WHERE e.salary = (SELECT MAX(salary) FROM employees);', 0),
        (253, 32, 'SELECT e.employee_id, e.salary, d.department_name FROM employees e JOIN departments d ON e.department_id = d.department_id ORDER BY e.salary DESC LIMIT 1;', 0),
        (254, 32, 'SELECT employee_id, salary FROM employees WHERE salary = (SELECT MIN(salary) FROM employees);', 0),
        (255, 32, 'SELECT e.employee_id, e.salary FROM employees e WHERE e.salary = (SELECT AVG(salary) FROM employees WHERE department_id = e.department_id);', 0),
        (256, 32, 'SELECT employee_id, salary FROM employees WHERE salary > 100000;', 0),
        (257, 33, 'Atomicity: 트랜잭션이 모두 성공하거나 전부 실패해야 한다. Consistency: 트랜잭션 후 데이터가 일관성을 유지해야 한다. Isolation: 트랜잭션 간 간섭이 없어야 한다. Durability: 트랜잭션이 완료되면 영구적으로 반영된다.', 1),
        (258, 33, 'Atomicity: 하나의 작업만 수행된다. Consistency: 데이터가 항상 동기화된다. Isolation: 모든 트랜잭션이 동시에 실행된다. Durability: 트랜잭션이 실패하면 롤백된다.', 0),
        (259, 33, 'Atomicity: 데이터베이스가 여러 작업을 동시에 처리할 수 있다. Consistency: 모든 데이터가 동기화된다. Isolation: 트랜잭션이 종료될 때까지 데이터를 잠근다. Durability: 데이터를 주기적으로 저장한다.', 0),
        (260, 33, 'Atomicity: 트랜잭션 중간에 데이터가 저장될 수 있다. Consistency: 무결성을 보장하지 않는다. Isolation: 여러 트랜잭션이 함께 실행된다. Durability: 데이터가 유지되지 않는다.', 0),
        (261, 33, 'ACID 원칙이란 데이터베이스의 성능을 높이는 기법이다.', 0),
        (262, 33, 'ACID 원칙을 준수하지 않는 경우 데이터는 영구적으로 손실된다.', 0),
        (263, 33, 'ACID 원칙은 NoSQL에서는 필요하지 않다.', 0),
        (264, 33, 'ACID 원칙은 트랜잭션이 실행되기 전에 데이터의 일관성을 보장한다.', 0),
        (265, 34, 'SELECT d.department_name FROM employees e JOIN departments d ON e.department_id = d.department_id GROUP BY d.department_name HAVING COUNT(*) >= 5;', 1),
        (266, 34, 'SELECT department_name FROM departments WHERE department_id IN (SELECT department_id FROM employees GROUP BY department_id HAVING COUNT(*) > 5);', 0),
        (267, 34, 'SELECT department_name FROM departments WHERE department_id IN (SELECT department_id FROM employees WHERE COUNT(*) >= 5);', 0),
        (268, 34, 'SELECT department_name FROM departments WHERE EXISTS (SELECT department_id FROM employees GROUP BY department_id HAVING COUNT(*) >= 5);', 0),
        (269, 34, 'SELECT d.department_name FROM departments d JOIN employees e ON d.department_id = e.department_id WHERE COUNT(e.employee_id) >= 5;', 0),
        (270, 34, 'SELECT department_name FROM departments WHERE COUNT(*) > 5;', 0),
        (271, 34, 'SELECT department_name FROM departments ORDER BY department_id LIMIT 5;', 0),
        (272, 34, 'SELECT department_name FROM departments WHERE department_id IN (SELECT department_id FROM employees GROUP BY department_id HAVING COUNT(*) < 5);', 0),
        (273, 35, '데이터 중복을 최소화하고 데이터 무결성을 유지하는 것', 1),
        (274, 35, '데이터베이스 성능을 높이기 위해 인덱스를 추가하는 것', 0),
        (275, 35, 'SQL 쿼리를 빠르게 실행하기 위해 데이터를 미리 저장하는 것', 0),
        (276, 35, '데이터를 암호화하여 보안성을 강화하는 것', 0),
        (277, 35, '데이터를 여러 개의 테이블로 나누지 않고 한 테이블에 저장하는 것', 0),
        (278, 35, '관계형 데이터베이스에서 트랜잭션을 보장하는 것', 0),
        (279, 35, '데이터를 한 곳에 집중하여 관리하는 것', 0),
        (280, 35, '데이터를 클러스터링하여 검색 속도를 빠르게 하는 것', 0),
        (281, 36, 'SELECT department_name FROM departments WHERE department_id = (SELECT department_id FROM employees GROUP BY department_id ORDER BY COUNT(*) DESC LIMIT 1);', 1),
        (282, 36, 'SELECT department_name FROM departments WHERE department_id = (SELECT department_id FROM employees GROUP BY department_id HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM employees GROUP BY department_id));', 0),
        (283, 36, 'SELECT department_name FROM departments ORDER BY (SELECT COUNT(*) FROM employees WHERE employees.department_id = departments.department_id) DESC LIMIT 1;', 0),
        (284, 36, 'SELECT department_name FROM departments WHERE department_id IN (SELECT department_id FROM employees GROUP BY department_id ORDER BY COUNT(*) ASC LIMIT 1);', 0),
        (285, 36, 'SELECT department_name FROM departments ORDER BY COUNT(employee_id) DESC LIMIT 1;', 0),
        (286, 36, 'SELECT department_name FROM departments WHERE department_id IN (SELECT department_id FROM employees GROUP BY department_id ORDER BY COUNT(*) DESC);', 0),
        (287, 36, 'SELECT department_name FROM departments WHERE department_id = (SELECT department_id FROM employees GROUP BY department_id HAVING COUNT(*) > 10);', 0),
        (288, 36, 'SELECT department_name FROM departments WHERE EXISTS (SELECT department_id FROM employees GROUP BY department_id ORDER BY COUNT(*) DESC LIMIT 1);', 0),
        (289, 37, 'SELECT e.employee_id, e.name FROM employees e INNER JOIN departments d ON e.department_id = d.department_id WHERE d.department_name = "IT";', 1),
        (290, 37, 'SELECT employee_id, name FROM employees WHERE department_id IN (SELECT department_id FROM departments WHERE department_name = "IT");', 0),
        (291, 37, 'SELECT e.employee_id, e.name FROM employees e LEFT JOIN departments d ON e.department_id = d.department_id WHERE d.department_name = "IT";', 0),
        (292, 37, 'SELECT employee_id, name FROM employees WHERE department_name = "IT";', 0),
        (293, 37, 'SELECT e.employee_id, e.name FROM employees e INNER JOIN departments d USING(department_id) WHERE d.department_name = "HR";', 0),
        (294, 37, 'SELECT employee_id, name FROM employees WHERE department_id = (SELECT department_id FROM departments WHERE department_name = "SALES");', 0),
        (295, 37, 'SELECT employee_id, name FROM employees WHERE department_id NOT IN (SELECT department_id FROM departments WHERE department_name = "IT");', 0),
        (296, 37, 'SELECT e.employee_id, e.name FROM employees e RIGHT JOIN departments d ON e.department_id = d.department_id WHERE d.department_name = "IT";', 0),
        (297, 38, 'SELECT DISTINCT department_name FROM departments;', 1),
        (298, 38, 'SELECT department_name FROM departments WHERE department_id IN (SELECT DISTINCT department_id FROM employees);', 0),
        (299, 38, 'SELECT DISTINCT department_id, department_name FROM departments;', 0),
        (300, 38, 'SELECT department_name FROM departments GROUP BY department_name;', 0),
        (301, 38, 'SELECT DISTINCT department_name FROM employees;', 0),
        (302, 38, 'SELECT department_name FROM departments WHERE department_name IS NOT NULL;', 0),
        (303, 38, 'SELECT department_name FROM departments ORDER BY department_name;', 0),
        (304, 38, 'SELECT department_name FROM departments HAVING COUNT(*) > 1;', 0),
        (305, 39, 'SELECT department_name, AVG(salary) FROM employees GROUP BY department_name HAVING AVG(salary) >= 5000;', 1),
        (306, 39, 'SELECT department_name FROM employees GROUP BY department_name WHERE AVG(salary) >= 5000;', 0),
        (307, 39, 'SELECT department_name FROM employees WHERE salary >= 5000;', 0),
        (308, 39, 'SELECT department_name, SUM(salary) FROM employees GROUP BY department_name HAVING SUM(salary) > 5000;', 0),
        (309, 39, 'SELECT department_name FROM employees GROUP BY department_name HAVING COUNT(*) > 5000;', 0),
        (310, 39, 'SELECT department_name FROM employees GROUP BY department_name ORDER BY AVG(salary) DESC LIMIT 1;', 0),
        (311, 39, 'SELECT department_name FROM employees WHERE EXISTS (SELECT department_name FROM employees GROUP BY department_name HAVING AVG(salary) >= 5000);', 0),
        (312, 39, 'SELECT department_name FROM employees GROUP BY department_name;', 0),
        (313, 40, 'SELECT name FROM current_employees UNION SELECT name FROM retired_employees;', 1),
        (314, 40, 'SELECT name FROM current_employees INNER JOIN retired_employees;', 0),
        (315, 40, 'SELECT name FROM current_employees WHERE status = "active" UNION SELECT name FROM retired_employees WHERE status = "retired";', 0),
        (316, 40, 'SELECT name FROM current_employees UNION ALL SELECT name FROM retired_employees;', 0),
        (317, 40, 'SELECT DISTINCT name FROM (SELECT name FROM current_employees UNION SELECT name FROM retired_employees) AS all_employees;', 0),
        (318, 40, 'SELECT name FROM employees WHERE status IN ("active", "retired");', 0),
        (319, 40, 'SELECT name FROM employees WHERE EXISTS (SELECT name FROM retired_employees);', 0),
        (320, 40, 'SELECT name FROM current_employees JOIN retired_employees;', 0),
        (321, 41, 'SELECT e.employee_id, e.name AS employee_name, m.employee_id AS manager_id, m.name AS manager_name FROM employees e LEFT JOIN employees m ON e.manager_id = m.employee_id;', 1),
        (322, 41, 'SELECT employee_id, name, manager_id FROM employees WHERE manager_id IS NOT NULL;', 0),
        (323, 41, 'SELECT employee_id, name FROM employees WHERE EXISTS (SELECT * FROM employees WHERE manager_id = employee_id);', 0),
        (324, 41, 'SELECT e.employee_id, e.name, e.manager_id FROM employees e INNER JOIN employees m ON e.employee_id = m.manager_id;', 0),
        (325, 41, 'SELECT e.employee_id, e.name, m.name AS manager_name FROM employees e RIGHT JOIN employees m ON e.manager_id = m.employee_id;', 0),
        (326, 41, 'SELECT e.employee_id, e.name FROM employees e WHERE e.manager_id IS NOT NULL;', 0),
        (327, 41, 'SELECT e.employee_id, e.name, m.name FROM employees e, employees m WHERE e.manager_id = m.employee_id;', 0),
        (328, 41, 'SELECT employee_id, name FROM employees WHERE department_id = (SELECT department_id FROM employees WHERE manager_id IS NOT NULL);', 0),
        (329, 42, 'START TRANSACTION; UPDATE accounts SET balance = balance - 500 WHERE account_id = 1; UPDATE accounts SET balance = balance + 500 WHERE account_id = 2; COMMIT;', 1),
        (330, 42, 'UPDATE accounts SET balance = balance - 500 WHERE account_id = 1; UPDATE accounts SET balance = balance + 500 WHERE account_id = 2;', 0),
        (331, 42, 'START TRANSACTION; UPDATE accounts SET balance = balance - 500 WHERE account_id = 1; COMMIT; UPDATE accounts SET balance = balance + 500 WHERE account_id = 2; COMMIT;', 0),
        (332, 42, 'BEGIN TRANSACTION; UPDATE accounts SET balance = balance - 500 WHERE account_id = 1; UPDATE accounts SET balance = balance + 500 WHERE account_id = 2; ROLLBACK;', 0),
        (333, 42, 'UPDATE accounts SET balance = balance + 500 WHERE account_id = 2; UPDATE accounts SET balance = balance - 500 WHERE account_id = 1;', 0),
        (334, 42, 'UPDATE accounts SET balance = balance - 500, balance = balance + 500 WHERE account_id IN (1, 2);', 0),
        (335, 42, 'UPDATE accounts SET balance = balance - 500 WHERE account_id = 1; COMMIT;', 0),
        (336, 42, 'UPDATE accounts SET balance = balance + 500 WHERE account_id = 2; COMMIT;', 0),
        (337, 43, 'UNION은 중복을 제거하고 UNION ALL은 중복을 포함한다.', 1),
        (338, 43, 'UNION과 UNION ALL은 동일하게 동작하며, 중복이 자동으로 제거된다.', 0),
        (339, 43, 'UNION은 결과를 정렬하고 UNION ALL은 정렬하지 않는다.', 0),
        (340, 43, 'UNION은 더 빠르지만 UNION ALL은 느리다.', 0),
        (341, 43, 'UNION은 두 개의 테이블을 결합하는 기능이다.', 0),
        (342, 43, 'UNION은 JOIN과 유사하지만, UNION ALL은 여러 개의 테이블을 결합한다.', 0),
        (343, 43, 'UNION과 UNION ALL은 둘 다 자동으로 중복을 포함한다.', 0),
        (344, 43, 'UNION은 하나의 테이블에서만 사용할 수 있고, UNION ALL은 여러 테이블에서 사용할 수 있다.', 0),
        (345, 44, 'SELECT employee_id, salary FROM employees WHERE salary = (SELECT MAX(salary) FROM employees);', 0),
        (346, 44, 'SELECT employee_id, salary FROM employees WHERE salary IN (SELECT MAX(salary) FROM employees GROUP BY department_id);', 1),
        (347, 44, 'SELECT employee_id, salary FROM employees WHERE salary = MAX(salary);', 0),
        (348, 44, 'SELECT employee_id, salary FROM employees GROUP BY department_id HAVING MAX(salary);', 0),
        (349, 44, 'SELECT employee_id, salary FROM employees WHERE salary = ALL (SELECT salary FROM employees GROUP BY department_id);', 0),
        (350, 44, 'SELECT employee_id, salary FROM employees WHERE department_id IN (SELECT department_id FROM employees WHERE salary = MAX(salary));', 0),
        (351, 44, 'SELECT employee_id, salary FROM employees WHERE EXISTS (SELECT salary FROM employees GROUP BY department_id HAVING MAX(salary));', 0),
        (352, 44, 'SELECT employee_id, salary FROM employees WHERE salary = (SELECT TOP 1 salary FROM employees ORDER BY salary DESC);', 0),
        (353, 45, '외래 키 제약 조건(Foreign Key Constraint) 때문', 1),
        (354, 45, '해당 데이터가 변경 불가능한 PRIMARY KEY이기 때문', 0),
        (355, 45, '데이터베이스가 특정 데이터를 삭제할 수 없도록 기본적으로 설정되어 있기 때문', 0),
        (356, 45, '자식 테이블의 데이터는 부모 테이블과 무관하기 때문', 0),
        (357, 45, 'CASCADE 옵션이 설정되지 않았기 때문', 0),
        (358, 45, 'DELETE 명령어는 기본적으로 자식 테이블 데이터를 자동으로 삭제하지 않기 때문', 0),
        (359, 45, '부모 테이블의 레코드는 변경 불가능한 데이터라서 삭제할 수 없기 때문', 0),
        (360, 45, 'DELETE 명령어는 오직 1개의 테이블에서만 실행할 수 있기 때문', 0),
        (361, 46, 'SELECT department_id, COUNT(*) FROM employees GROUP BY department_id;', 1),
        (362, 46, 'SELECT department_id, SUM(*) FROM employees GROUP BY department_id;', 0),
        (364, 46, 'SELECT department_id, AVG(employee_id) FROM employees GROUP BY department_id;', 0),
        (365, 46, 'SELECT department_id FROM employees GROUP BY department_id HAVING COUNT(*) > 0;', 0),
        (366, 46, 'SELECT department_id, COUNT(*) FROM employees WHERE department_id GROUP BY department_id;', 0),
        (367, 46, 'SELECT COUNT(*) FROM employees WHERE department_id GROUP BY department_id;', 0),
        (368, 46, 'SELECT department_id, employee_id FROM employees WHERE COUNT(*) > 1;', 0),
        (369, 47, 'SELECT department_id, COUNT(DISTINCT job_title) FROM employees GROUP BY department_id;', 1),
        (370, 47, 'SELECT department_id, COUNT(job_title) FROM employees GROUP BY department_id;', 0),
        (371, 47, 'SELECT DISTINCT department_id, COUNT(job_title) FROM employees GROUP BY department_id;', 0),
        (372, 47, 'SELECT department_id, DISTINCT COUNT(job_title) FROM employees GROUP BY department_id;', 0),
        (373, 47, 'SELECT department_id, COUNT(job_title) FROM employees;', 0),
        (375, 47, 'SELECT DISTINCT department_id, COUNT(DISTINCT job_title) FROM employees;', 0),
        (376, 47, 'SELECT department_id, COUNT(*) FROM employees WHERE DISTINCT job_title;', 0),
        (377, 48, 'SELECT student_id, AVG(grade) AS avg_grade FROM grades GROUP BY student_id HAVING avg_grade >= 3.5;', 1),
        (378, 48, 'SELECT student_id, AVG(grade) FROM grades GROUP BY student_id WHERE AVG(grade) >= 3.5;', 0),
        (379, 48, 'SELECT student_id FROM grades GROUP BY student_id WHERE AVG(grade) >= 3.5;', 0),
        (380, 48, 'SELECT student_id, AVG(grade) AS avg_grade FROM grades WHERE avg_grade >= 3.5 GROUP BY student_id;', 0),
        (381, 48, 'SELECT student_id, COUNT(grade) FROM grades GROUP BY student_id HAVING COUNT(grade) > 3;', 0),
        (383, 48, 'SELECT student_id FROM grades WHERE AVG(grade) >= 3.5;', 0),
        (384, 48, 'SELECT student_id, grade FROM grades WHERE grade >= 3.5;', 0),
        (385, 49, 'SELECT product_id, COUNT(*) AS order_count FROM orders GROUP BY product_id ORDER BY order_count DESC LIMIT 1;', 1),
        (386, 49, 'SELECT product_id FROM orders WHERE COUNT(product_id) = MAX(product_id);', 0),
        (387, 49, 'SELECT product_id, COUNT(product_id) AS order_count FROM orders GROUP BY product_id HAVING COUNT(*) >= 1;', 0),
        (388, 49, 'SELECT product_id FROM orders WHERE COUNT(*) = MAX(COUNT(*));', 0),
        (390, 49, 'SELECT product_id FROM orders GROUP BY product_id HAVING MAX(product_id);', 0),
        (391, 49, 'SELECT product_id, COUNT(*) FROM orders GROUP BY product_id ORDER BY COUNT(*) ASC LIMIT 1;', 0),
        (392, 49, 'SELECT product_id, COUNT(*) FROM orders GROUP BY product_id;', 0),
        (393, 50, 'SELECT book_id, student_id FROM library_loans WHERE return_date IS NULL;', 1),
        (394, 50, 'SELECT book_id FROM library_loans WHERE return_date = NULL;', 0),
        (395, 50, 'SELECT book_id FROM library_loans WHERE return_date = 0;', 0),
        (396, 50, 'SELECT book_id, COUNT(*) FROM library_loans WHERE return_date IS NULL;', 0),
        (397, 50, 'SELECT book_id FROM library_loans WHERE return_date != "RETURNED";', 0),
        (398, 50, 'SELECT book_id, student_id FROM library_loans WHERE return_date = "NULL";', 0),
        (399, 50, 'SELECT book_id FROM library_loans WHERE return_date != 1;', 0),
        (400, 50, 'SELECT book_id FROM library_loans WHERE return_date IS NOT NULL;', 0),
        (401, 51, 'SELECT * FROM orders WHERE YEAR(order_date) = 2024 AND MONTH(order_date) = 5;', 1),
        (403, 51, 'SELECT * FROM orders WHERE DATE_FORMAT(order_date, "%Y-%m") = "2024-05";', 0),
        (404, 51, 'SELECT * FROM orders WHERE EXTRACT(YEAR_MONTH FROM order_date) = 202405;', 0),
        (405, 51, 'SELECT * FROM orders WHERE order_date LIKE "2024-05%";', 0),
        (406, 51, 'SELECT * FROM orders WHERE MONTH(order_date) = 5;', 0),
        (407, 51, 'SELECT * FROM orders WHERE order_date = "2024-05";', 0),
        (408, 51, 'SELECT * FROM orders WHERE YEAR(order_date) = 2024;', 0),
        (409, 52, 'CREATE VIEW student_avg_scores AS SELECT student_id, AVG(score) AS avg_score FROM grades GROUP BY student_id;', 1),
        (410, 52, 'CREATE OR REPLACE VIEW student_avg_scores AS SELECT student_id, COUNT(score) FROM grades;', 0),
        (411, 52, 'CREATE TABLE student_avg_scores AS SELECT student_id, AVG(score) FROM grades GROUP BY student_id;', 0),
        (412, 52, 'SELECT * FROM student_avg_scores WHERE avg_score > 80;', 0),
        (413, 52, 'ALTER VIEW student_avg_scores AS SELECT student_id, AVG(score) FROM grades;', 0),
        (414, 52, 'CREATE VIEW student_avg_scores (student_id, avg_score) AS SELECT student_id, AVG(score) FROM grades;', 0),
        (415, 52, 'UPDATE student_avg_scores SET avg_score = 90 WHERE student_id = 3;', 0),
        (416, 52, 'DROP VIEW student_avg_scores;', 0),
        (417, 53, 'SELECT employee_id, name, salary, department_id FROM employees e WHERE salary > (SELECT AVG(salary) FROM employees WHERE department_id = e.department_id);', 1),
        (418, 53, 'SELECT employee_id, name, salary FROM employees WHERE salary > AVG(salary) GROUP BY department_id;', 0),
        (419, 53, 'SELECT employee_id, name, salary FROM employees HAVING salary > (SELECT AVG(salary) FROM employees);', 0),
        (420, 53, 'SELECT employee_id, name, salary FROM employees WHERE department_id IN (SELECT department_id FROM employees WHERE salary > AVG(salary));', 0),
        (421, 53, 'SELECT * FROM employees WHERE salary > (SELECT MAX(salary) FROM employees);', 0),
        (422, 53, 'SELECT * FROM employees WHERE salary > ALL (SELECT salary FROM employees);', 0),
        (423, 53, 'SELECT employee_id, salary FROM employees WHERE salary = (SELECT MIN(salary) FROM employees);', 0),
        (424, 53, 'SELECT department_id, AVG(salary) FROM employees GROUP BY department_id;', 0),
        (425, 54, 'SELECT product_id, name, price, CASE WHEN price >= 50000 THEN "고가" WHEN price >= 20000 THEN "중가" ELSE "저가" END AS price_grade FROM products;', 1),
        (426, 54, 'SELECT product_id, name, price FROM products WHERE price IN ("고가", "중가", "저가");', 0),
        (427, 54, 'SELECT product_id, name, price FROM products WHERE price > 50000 THEN "고가";', 0),
        (428, 54, 'SELECT product_id, name, price, CASE WHEN price > 50000 THEN "고가" END FROM products;', 0),
        (429, 54, 'SELECT product_id, price FROM products GROUP BY price HAVING COUNT(*) > 1;', 0),
        (430, 54, 'SELECT product_id, name FROM products WHERE price IN (50000, 20000, 10000);', 0),
        (431, 54, 'SELECT * FROM products WHERE CASE WHEN price >= 50000 THEN "고가";', 0),
        (432, 54, 'SELECT product_id, name, price, "고가" AS price_grade FROM products WHERE price >= 50000;', 0),
        (433, 55, 'SELECT customer_id, name, "신규 고객" AS customer_type FROM customers WHERE join_date >= "2023-01-01" UNION SELECT customer_id, name, "기존 고객" AS customer_type FROM customers WHERE join_date < "2023-01-01";', 1),
        (435, 55, 'SELECT customer_id, name FROM customers WHERE join_date IN ("신규 고객", "기존 고객");', 0),
        (436, 55, 'SELECT customer_id, name, join_date FROM customers WHERE join_date >= "2023-01-01" OR join_date < "2023-01-01";', 0),
        (437, 55, 'SELECT customer_id, name, "신규 고객" FROM customers WHERE join_date >= "2023-01-01";', 0),
        (438, 55, 'SELECT customer_id, name FROM customers WHERE join_date = "2023년 이후";', 0),
        (439, 55, 'SELECT customer_id FROM customers WHERE join_date BETWEEN "2023-01-01" AND "2024-01-01";', 0),
        (440, 55, 'SELECT customer_id, name FROM customers GROUP BY join_date;', 0),
        (441, 56, 'START TRANSACTION; UPDATE orders SET status = "CANCELLED" WHERE order_id = 101; DELETE FROM payments WHERE order_id = 101; COMMIT;', 1),
        (442, 56, 'UPDATE orders SET status = "CANCELLED" WHERE order_id = 101; DELETE FROM payments WHERE order_id = 101;', 0),
        (444, 56, 'ROLLBACK TRANSACTION; UPDATE orders SET status = "CANCELLED" WHERE order_id = 101; DELETE FROM payments WHERE order_id = 101;', 0),
        (445, 56, 'SET AUTOCOMMIT = 0; DELETE FROM payments WHERE order_id = 101; UPDATE orders SET status = "CANCELLED" WHERE order_id = 101;', 0),
        (446, 56, 'SAVEPOINT cancel_order; UPDATE orders SET status = "CANCELLED" WHERE order_id = 101; DELETE FROM payments WHERE order_id = 101;', 0),
        (447, 56, 'START TRANSACTION; DELETE FROM payments WHERE order_id = 101; COMMIT;', 0),
        (448, 56, 'COMMIT; UPDATE orders SET status = "CANCELLED" WHERE order_id = 101;', 0),
        (449, 57, 'SELECT employee_id, name, department_id, salary, RANK() OVER (PARTITION BY department_id ORDER BY salary DESC) AS rank FROM employees;', 1),
        (450, 57, 'SELECT employee_id, name, salary FROM employees WHERE salary > (SELECT AVG(salary) FROM employees);', 0),
        (451, 57, 'SELECT employee_id, name, department_id, salary FROM employees ORDER BY salary DESC;', 0),
        (453, 57, 'SELECT employee_id, name, department_id, salary, RANK() OVER (ORDER BY salary DESC) FROM employees;', 0),
        (455, 57, 'SELECT employee_id, name, salary FROM employees WHERE salary >= ALL (SELECT salary FROM employees);', 0),
        (456, 57, 'SELECT employee_id, name FROM employees ORDER BY salary DESC;', 0),
        (457, 58, 'SELECT e.employee_id, e.name AS employee_name, m.name AS manager_name FROM employees e LEFT JOIN employees m ON e.manager_id = m.employee_id;', 1),
        (458, 58, 'SELECT employee_id, name, manager_id FROM employees WHERE manager_id IS NOT NULL;', 0),
        (459, 58, 'SELECT employee_id, name FROM employees WHERE manager_id = employee_id;', 0),
        (462, 58, 'SELECT employee_id, name, manager_id FROM employees ORDER BY manager_id;', 0),
        (463, 58, 'SELECT * FROM employees WHERE employee_id IN (SELECT manager_id FROM employees);', 0),
        (464, 58, 'SELECT e.employee_id, e.name FROM employees e INNER JOIN employees m ON e.manager_id = m.manager_id;', 0),
        (465, 59, 'SELECT email, SUBSTRING_INDEX(email, "@", -1) AS domain FROM employees;', 1),
        (466, 59, 'SELECT email, LEFT(email, LOCATE("@", email)) AS domain FROM employees;', 0),
        (467, 59, 'SELECT email, RIGHT(email, LOCATE("@", email)) FROM employees;', 0),
        (469, 59, 'SELECT email, SUBSTRING_INDEX(email, "@", 1) AS domain FROM employees;', 0),
        (470, 59, 'SELECT email, REPLACE(email, "@", "") FROM employees;', 0),
        (471, 59, 'SELECT email, TRIM("@", email) FROM employees;', 0),
        (472, 59, 'SELECT email, SPLIT_PART(email, "@", 2) FROM employees;', 0),
        (473, 60, 'SELECT department_id, GROUP_CONCAT(name ORDER BY name ASC SEPARATOR ", ") AS employee_names FROM employees GROUP BY department_id;', 1),
        (474, 60, 'SELECT department_id, LISTAGG(name, ", ") FROM employees GROUP BY department_id;', 0),
        (475, 60, 'SELECT department_id, STRING_AGG(name, ", ") FROM employees GROUP BY department_id;', 0),
        (477, 60, 'SELECT department_id, COUNT(name) FROM employees GROUP BY department_id;', 0),
        (479, 60, 'SELECT department_id, REPLACE(name, ",", " ") FROM employees GROUP BY department_id;', 0),
        (480, 60, 'SELECT department_id, CONCAT(name) FROM employees GROUP BY department_id;', 0),
        (481, 61, 'SELECT student_id, name FROM students WHERE score = MAX(score);', 0),
        (482, 61, 'SELECT student_id, name, score FROM students s WHERE score = (SELECT MAX(score) FROM students s2 WHERE s.class_id = s2.class_id);', 1),
        (483, 61, 'SELECT student_id, name FROM students ORDER BY score DESC LIMIT 1;', 0),
        (484, 61, 'SELECT student_id, name, MAX(score) FROM students;', 0),
        (485, 61, 'SELECT * FROM students WHERE score > (SELECT AVG(score) FROM students);', 0),
        (486, 61, 'SELECT student_id, name FROM students WHERE score = (SELECT MIN(score) FROM students);', 0),
        (487, 61, 'SELECT student_id, name FROM students WHERE score BETWEEN 80 AND 100;', 0),
        (488, 61, 'SELECT student_id, name, score FROM students ORDER BY class_id;', 0),
        (489, 62, 'WITH EmployeeHierarchy AS (SELECT * FROM employees WHERE manager_id = 5);', 0),
        (490, 62, 'SELECT employee_id, name FROM employees WHERE manager_id = 5;', 0),
        (491, 62, 'WITH RECURSIVE EmployeeHierarchy AS (SELECT employee_id, name, manager_id FROM employees WHERE employee_id = 5 UNION ALL SELECT e.employee_id, e.name, e.manager_id FROM employees e JOIN EmployeeHierarchy eh ON e.manager_id = eh.employee_id) SELECT * FROM EmployeeHierarchy;', 1),
        (492, 62, 'SELECT employee_id, name FROM employees ORDER BY manager_id;', 0),
        (493, 62, 'SELECT * FROM employees WHERE manager_id IN (SELECT employee_id FROM employees WHERE manager_id = 5);', 0),
        (494, 62, 'SELECT employee_id, name FROM employees WHERE manager_id = (SELECT manager_id FROM employees WHERE employee_id = 5);', 0),
        (495, 62, 'SELECT employee_id, name FROM employees WHERE employee_id = 5;', 0),
        (496, 62, 'SELECT employee_id, name FROM employees WHERE manager_id IS NOT NULL;', 0),
        (497, 63, 'SELECT sale_month, SUM(amount) FROM sales GROUP BY sale_month;', 0),
        (498, 63, 'SELECT sale_month, SUM(amount) AS total_sales FROM sales PARTITION (p_202401) GROUP BY sale_month;', 1),
        (499, 63, 'SELECT * FROM sales WHERE sale_month = ''2024-01'';', 0),
        (500, 63, 'SELECT sale_month, SUM(amount) FROM sales WHERE sale_month = ''2024-01'' GROUP BY sale_month;', 0),
        (501, 63, 'SELECT sale_month, AVG(amount) FROM sales GROUP BY sale_month;', 0),
        (502, 63, 'SELECT * FROM sales WHERE amount > 1000;', 0),
        (503, 63, 'SELECT sale_month, SUM(amount) FROM sales PARTITION (p_202312) GROUP BY sale_month;', 0),
        (504, 63, 'SELECT sale_month, COUNT(*) FROM sales GROUP BY sale_month;', 0),
        (505, 64, 'SELECT sale_month, AVG(total_sales) OVER (ORDER BY sale_month ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS avg_sales FROM sales;', 1),
        (506, 64, 'SELECT sale_month, SUM(amount) FROM sales GROUP BY sale_month;', 0),
        (507, 64, 'SELECT sale_month, LAG(total_sales, 3) OVER (PARTITION BY sale_month) FROM sales;', 0),
        (508, 64, 'SELECT AVG(amount) FROM sales WHERE sale_month BETWEEN CURDATE() - INTERVAL 3 MONTH AND CURDATE();', 0),
        (509, 64, 'SELECT sale_month, SUM(amount) OVER (ORDER BY sale_month RANGE BETWEEN 2 PRECEDING AND CURRENT ROW) AS avg_sales FROM sales;', 0),
        (510, 64, 'SELECT sale_month, MAX(amount) FROM sales GROUP BY sale_month;', 0),
        (511, 64, 'SELECT sale_month, SUM(amount) OVER (PARTITION BY sale_month) FROM sales;', 0),
        (512, 64, 'SELECT sale_month, COUNT(amount) FROM sales GROUP BY sale_month;', 0),
        (513, 65, 'SELECT product_id, product_name FROM sales WHERE quantity = (SELECT MAX(quantity) FROM sales);', 1),
        (514, 65, 'SELECT product_id, product_name, SUM(quantity) FROM sales GROUP BY product_id ORDER BY SUM(quantity) DESC LIMIT 1;', 0),
        (515, 65, 'SELECT product_id, COUNT(*) FROM sales GROUP BY product_id;', 0),
        (516, 65, 'SELECT * FROM sales ORDER BY quantity DESC;', 0),
        (517, 65, 'SELECT product_id FROM sales WHERE quantity > (SELECT AVG(quantity) FROM sales);', 0),
        (518, 65, 'SELECT product_id, product_name FROM sales WHERE quantity = (SELECT MIN(quantity) FROM sales);', 0),
        (519, 65, 'SELECT product_id, product_name FROM sales WHERE quantity BETWEEN 100 AND 500;', 0),
        (520, 65, 'SELECT product_id, product_name, SUM(quantity) FROM sales WHERE sale_date >= NOW() - INTERVAL 30 DAY GROUP BY product_id ORDER BY SUM(quantity) DESC;', 0),
        (522, 66, 'SELECT customer_id, COUNT(*) FROM orders WHERE customer_id = 1001;', 0),
        (523, 66, 'SELECT customer_id, MAX(total_amount) FROM orders WHERE customer_id = 1001;', 0),
        (524, 66, 'SELECT SUM(total_amount) FROM orders;', 0),
        (525, 66, 'SELECT SUM(total_amount) FROM orders WHERE customer_id = 1001;', 1),
        (526, 66, 'SELECT customer_id, SUM(amount) FROM orders WHERE order_id = 1001;', 0),
        (527, 66, 'SELECT * FROM orders WHERE customer_id = 1001;', 0),
        (528, 66, 'SELECT customer_id, total_amount FROM orders WHERE total_amount > 500;', 0),
        (529, 67, 'WITH RECURSIVE CategoryHierarchy AS (SELECT category_id, parent_category_id FROM categories WHERE category_id = 10 UNION ALL SELECT c.category_id, c.parent_category_id FROM categories c JOIN CategoryHierarchy ch ON c.parent_category_id = ch.category_id) SELECT * FROM CategoryHierarchy;', 1),
        (530, 67, 'SELECT category_id FROM categories WHERE parent_category_id = 10;', 0),
        (531, 67, 'SELECT * FROM categories WHERE category_id = 10;', 0),
        (532, 67, 'SELECT category_id FROM categories ORDER BY parent_category_id;', 0),
        (533, 67, 'WITH RECURSIVE CategoryHierarchy AS (SELECT category_id FROM categories WHERE parent_category_id = 10) SELECT * FROM CategoryHierarchy;', 0),
        (534, 67, 'SELECT * FROM categories WHERE parent_category_id = (SELECT category_id FROM categories WHERE category_id = 10);', 0),
        (535, 67, 'SELECT category_id, category_name FROM categories WHERE parent_category_id IN (SELECT category_id FROM categories WHERE parent_category_id = 10);', 0),
        (536, 67, 'SELECT category_id, category_name FROM categories ORDER BY category_id;', 0),
        (537, 68, 'SELECT * FROM user_logs PARTITION (p_202401) WHERE log_date = ''2024-01-15'';', 1),
        (538, 68, 'SELECT * FROM user_logs WHERE log_date = ''2024-01-15'';', 0),
        (539, 68, 'SELECT log_date, COUNT(*) FROM user_logs GROUP BY log_date;', 0),
        (540, 68, 'SELECT * FROM user_logs WHERE user_id = 1234;', 0),
        (541, 68, 'SELECT COUNT(*) FROM user_logs WHERE log_date = ''2024-01-15'';', 0),
        (542, 68, 'SELECT * FROM user_logs PARTITION (p_202312) WHERE log_date = ''2023-12-31'';', 0),
        (543, 68, 'SELECT user_id, COUNT(*) FROM user_logs WHERE log_date = ''2024-01-15'' GROUP BY user_id;', 0),
        (544, 68, 'SELECT * FROM user_logs WHERE log_type = ''ERROR'';', 0),
        (545, 69, 'SELECT customer_id, order_month, sales, (sales - LAG(sales) OVER (PARTITION BY customer_id ORDER BY order_month)) / LAG(sales) OVER (PARTITION BY customer_id ORDER BY order_month) * 100 AS growth_rate FROM customer_sales;', 1),
        (546, 69, 'SELECT customer_id, order_month, sales FROM customer_sales GROUP BY customer_id, order_month;', 0),
        (547, 69, 'SELECT customer_id, order_month, sales, SUM(sales) OVER (PARTITION BY customer_id) FROM customer_sales;', 0),
        (548, 69, 'SELECT customer_id, AVG(sales) FROM customer_sales GROUP BY customer_id;', 0),
        (549, 69, 'SELECT * FROM customer_sales ORDER BY order_month;', 0),
        (550, 69, 'SELECT customer_id, order_month, sales FROM customer_sales WHERE sales > 1000;', 0),
        (551, 69, 'SELECT customer_id, sales FROM customer_sales WHERE order_month BETWEEN NOW() - INTERVAL 3 MONTH AND NOW();', 0),
        (552, 69, 'SELECT customer_id, SUM(sales) FROM customer_sales GROUP BY customer_id, order_month;', 0),
        (553, 70, 'SELECT category_id, brand_id, SUM(sales) FROM sales GROUP BY GROUPING SETS ((category_id), (brand_id), ());', 1),
        (554, 70, 'SELECT category_id, brand_id, SUM(sales) FROM sales GROUP BY category_id, brand_id;', 0),
        (555, 70, 'SELECT category_id, SUM(sales) FROM sales WHERE brand_id IS NOT NULL GROUP BY category_id;', 0),
        (556, 70, 'SELECT category_id, brand_id FROM sales WHERE sales > 5000;', 0),
        (557, 70, 'SELECT brand_id, SUM(sales) FROM sales GROUP BY brand_id;', 0),
        (558, 70, 'SELECT category_id, brand_id, AVG(sales) FROM sales GROUP BY category_id, brand_id;', 0),
        (559, 70, 'SELECT category_id, SUM(sales) FROM sales WHERE sales > 10000;', 0),
        (560, 70, 'SELECT category_id FROM sales GROUP BY category_id;', 0),
        (561, 71, 'SELECT customer_id, name FROM customers WHERE NOT EXISTS (SELECT 1 FROM orders WHERE customers.customer_id = orders.customer_id);', 1),
        (562, 71, 'SELECT customer_id, name FROM customers LEFT JOIN orders ON customers.customer_id = orders.customer_id WHERE orders.customer_id IS NULL;', 0),
        (563, 71, 'SELECT customer_id, name FROM customers WHERE customer_id NOT IN (SELECT customer_id FROM orders);', 0),
        (564, 71, 'SELECT customer_id, name FROM customers WHERE customer_id IN (SELECT customer_id FROM orders);', 0),
        (565, 71, 'SELECT customer_id, COUNT(order_id) FROM orders GROUP BY customer_id;', 0),
        (566, 71, 'SELECT customer_id, name FROM customers WHERE name LIKE ''%김%'';', 0),
        (567, 71, 'SELECT DISTINCT customer_id FROM orders;', 0),
        (568, 71, 'SELECT * FROM customers WHERE EXISTS (SELECT 1 FROM orders WHERE orders.customer_id = customers.customer_id);', 0),
        (569, 72, 'SELECT department_id, employee_id, salary, RANK() OVER (PARTITION BY department_id ORDER BY salary DESC) AS salary_rank FROM employees;', 1),
        (570, 72, 'SELECT department_id, employee_id, salary FROM employees GROUP BY department_id, employee_id;', 0),
        (571, 72, 'SELECT employee_id, salary FROM employees WHERE salary > 5000;', 0),
        (572, 72, 'SELECT department_id, employee_id, salary FROM employees ORDER BY salary DESC;', 0),
        (573, 72, 'SELECT department_id, MAX(salary) FROM employees GROUP BY department_id;', 0),
        (574, 72, 'SELECT department_id, employee_id, AVG(salary) FROM employees GROUP BY department_id;', 0),
        (575, 72, 'SELECT department_id, employee_id FROM employees WHERE salary > 10000;', 0),
        (576, 72, 'SELECT employee_id, salary FROM employees GROUP BY department_id;', 0),
        (577, 73, 'SELECT MONTH(order_date) AS month, SUM(sales) FROM orders GROUP BY GROUPING SETS ((MONTH(order_date)), ());', 1),
        (578, 73, 'SELECT order_date, SUM(sales) FROM orders GROUP BY order_date;', 0),
        (579, 73, 'SELECT category_id, SUM(sales) FROM orders GROUP BY category_id;', 0),
        (580, 73, 'SELECT order_date, SUM(sales) FROM orders WHERE sales > 10000;', 0),
        (581, 73, 'SELECT SUM(sales) FROM orders;', 0),
        (582, 73, 'SELECT MONTH(order_date), AVG(sales) FROM orders GROUP BY MONTH(order_date);', 0),
        (583, 73, 'SELECT category_id, order_date, SUM(sales) FROM orders GROUP BY category_id, order_date;', 0),
        (584, 73, 'SELECT order_date, SUM(sales) FROM orders WHERE order_status = ''SHIPPED'' GROUP BY order_date;', 0),
        (585, 74, 'SELECT department_id, employee_id, hire_date, FIRST_VALUE(employee_id) OVER (PARTITION BY department_id ORDER BY hire_date DESC) AS newest_employee FROM employees;', 1),
        (586, 74, 'SELECT department_id, employee_id, hire_date FROM employees WHERE hire_date = (SELECT MAX(hire_date) FROM employees);', 0),
        (587, 74, 'SELECT department_id, employee_id FROM employees ORDER BY hire_date DESC;', 0),
        (588, 74, 'SELECT department_id, employee_id FROM employees WHERE hire_date > NOW() - INTERVAL 1 YEAR;', 0),
        (589, 74, 'SELECT department_id, employee_id FROM employees WHERE hire_date BETWEEN NOW() - INTERVAL 1 YEAR AND NOW();', 0),
        (590, 74, 'SELECT department_id, MIN(hire_date) FROM employees GROUP BY department_id;', 0),
        (591, 74, 'SELECT employee_id FROM employees WHERE department_id IS NOT NULL;', 0),
        (592, 74, 'SELECT department_id, COUNT(employee_id) FROM employees GROUP BY department_id;', 0),
        (593, 75, 'SELECT category_id, brand_id, SUM(sales) FROM sales GROUP BY GROUPING SETS ((category_id), (brand_id), ());', 1),
        (594, 75, 'SELECT category_id, brand_id, SUM(sales) FROM sales GROUP BY category_id, brand_id;', 0),
        (595, 75, 'SELECT brand_id, SUM(sales) FROM sales WHERE category_id IS NOT NULL GROUP BY brand_id;', 0),
        (596, 75, 'SELECT category_id, brand_id FROM sales WHERE sales > 5000;', 0),
        (597, 75, 'SELECT brand_id, SUM(sales) FROM sales GROUP BY brand_id;', 0),
        (598, 75, 'SELECT category_id, brand_id, AVG(sales) FROM sales GROUP BY category_id, brand_id;', 0),
        (599, 75, 'SELECT category_id, SUM(sales) FROM sales WHERE sales > 10000;', 0),
        (600, 75, 'SELECT category_id FROM sales GROUP BY category_id;', 0),
        (601, 76, 'SELECT customer_id, name FROM customers WHERE NOT EXISTS (SELECT 1 FROM orders WHERE customers.customer_id = orders.customer_id AND product_id = "Product A");', 1),
        (602, 76, 'SELECT customer_id, name FROM customers WHERE customer_id NOT IN (SELECT customer_id FROM orders WHERE product_id = "Product A");', 0),
        (603, 76, 'SELECT customer_id, name FROM customers WHERE customer_id IN (SELECT customer_id FROM orders);', 0),
        (604, 76, 'SELECT DISTINCT customer_id FROM orders WHERE product_id = "Product A";', 0),
        (605, 76, 'SELECT customer_id, name FROM customers WHERE customer_id IN (SELECT customer_id FROM orders WHERE order_status = "SHIPPED");', 0),
        (606, 76, 'SELECT * FROM customers WHERE EXISTS (SELECT 1 FROM orders WHERE orders.customer_id = customers.customer_id);', 0),
        (607, 76, 'SELECT customer_id FROM orders WHERE product_id = "Product A";', 0),
        (608, 76, 'SELECT customer_id, name FROM customers WHERE name LIKE ''%김%'';', 0),
        (609, 77, 'SELECT student_id, exam_date, score, AVG(score) OVER (PARTITION BY student_id ORDER BY exam_date ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS avg_score FROM student_scores;', 1),
        (610, 77, 'SELECT student_id, AVG(score) FROM student_scores GROUP BY student_id;', 0),
        (611, 77, 'SELECT student_id, score FROM student_scores WHERE score > 80;', 0),
        (612, 77, 'SELECT student_id, score FROM student_scores ORDER BY exam_date DESC;', 0),
        (613, 77, 'SELECT student_id, MAX(score) FROM student_scores GROUP BY student_id;', 0),
        (614, 77, 'SELECT student_id, COUNT(score) FROM student_scores GROUP BY student_id;', 0),
        (615, 77, 'SELECT student_id, MIN(score) FROM student_scores GROUP BY student_id;', 0),
        (616, 77, 'SELECT student_id, exam_date, score FROM student_scores WHERE exam_date BETWEEN NOW() - INTERVAL 6 MONTH AND NOW();', 0),
        (617, 78, 'GROUPING SETS는 특정한 집계 조합을 지정할 수 있으며, ROLLUP은 계층적 집계를 수행한다.', 1),
        (618, 78, 'ROLLUP과 CUBE는 동일한 기능을 수행하며, GROUPING SETS는 이를 포함하는 상위 개념이다.', 0),
        (619, 78, 'GROUPING SETS는 개별 열을 기준으로 자동 집계를 수행하는 기능이다.', 0),
        (620, 78, 'CUBE는 ROLLUP의 하위 개념이며, GROUPING SETS는 모든 가능한 조합을 집계한다.', 0),
        (621, 78, 'GROUPING SETS는 하나의 열만 집계할 수 있으며, 다중 열을 지원하지 않는다.', 0),
        (622, 78, 'ROLLUP과 GROUPING SETS는 동일한 기능을 수행하며, CUBE만 다르다.', 0),
        (623, 78, 'ROLLUP은 특정 컬럼에 대한 총합을 구할 때 사용되며, GROUPING SETS는 이를 최적화한 버전이다.', 0),
        (625, 79, '윈도우 함수는 개별 행을 보존하며, GROUP BY를 사용하지 않고도 집계 연산을 수행할 수 있다.', 1),
        (626, 79, '일반 집계 함수는 개별 행을 유지하며, 윈도우 함수는 데이터를 집계하여 하나의 값으로 축소한다.', 0),
        (627, 79, '윈도우 함수는 반드시 GROUP BY와 함께 사용해야 한다.', 0),
        (628, 79, '윈도우 함수는 단순히 SUM, COUNT와 같은 기본 연산을 수행하는 함수이다.', 0),
        (629, 79, '집계 함수는 WHERE 절과 함께 사용할 수 있지만, 윈도우 함수는 사용할 수 없다.', 0),
        (630, 79, '윈도우 함수는 단순히 데이터를 정렬하는 기능만을 수행한다.', 0),
        (631, 79, '일반 집계 함수는 행별로 계산되며, 윈도우 함수는 그룹 전체에 대해 한 번만 계산된다.', 0),
        (633, 80, 'NOT EXISTS는 특정 서브쿼리에 해당하는 행이 존재하지 않는 경우 TRUE를 반환한다.', 1),
        (634, 80, 'LEFT JOIN과 NOT EXISTS는 동일한 기능을 수행하며, 성능 차이는 거의 없다.', 0),
        (635, 80, 'NOT EXISTS는 INNER JOIN을 포함하는 경우에만 사용할 수 있다.', 0),
        (636, 80, 'LEFT JOIN을 사용하면 NOT EXISTS보다 성능이 향상된다.', 0),
        (637, 80, 'NOT EXISTS는 NULL 값을 허용하지 않으며, LEFT JOIN은 NULL을 포함할 수 있다.', 0),
        (638, 80, 'LEFT JOIN은 필터링을 위해 사용되지만, NOT EXISTS는 데이터 조회용으로만 사용된다.', 0),
        (639, 80, 'LEFT JOIN과 NOT EXISTS는 서브쿼리를 사용할 필요 없이 동일한 결과를 반환한다.', 0),
        (641, 81, 'PARTITION BY는 개별 행을 유지하며, 그룹 내에서 연산을 수행할 수 있다.', 1),
        (642, 81, 'GROUP BY는 개별 행을 보존하면서 그룹화된 데이터를 조회하는 기능을 제공한다.', 0),
        (643, 81, 'PARTITION BY는 그룹화된 데이터의 개수를 줄이는 역할을 한다.', 0),
        (644, 81, 'GROUP BY는 반드시 PARTITION BY와 함께 사용해야 한다.', 0),
        (645, 81, 'PARTITION BY는 SUM과 같은 집계 함수와 함께 사용할 수 없다.', 0),
        (646, 81, 'GROUP BY는 개별 행을 유지하면서 데이터를 정렬하는 기능을 한다.', 0),
        (647, 81, 'PARTITION BY는 GROUP BY의 상위 개념이며, 모든 집계 함수에 적용할 수 있다.', 0),
        (649, 82, 'SELECT customer_id, COUNT(*) AS total_orders FROM orders GROUP BY customer_id ORDER BY total_orders DESC LIMIT 1;', 1),
        (650, 82, 'SELECT customer_id FROM orders WHERE COUNT(order_id) = MAX(COUNT(order_id));', 0),
        (651, 82, 'SELECT customer_id, SUM(order_amount) FROM orders GROUP BY customer_id HAVING SUM(order_amount) > 1000;', 0),
        (652, 82, 'SELECT DISTINCT customer_id FROM orders WHERE total_orders = (SELECT MAX(total_orders) FROM orders);', 0),
        (654, 82, 'SELECT customer_id FROM customers WHERE order_count = (SELECT MAX(order_count) FROM customers);', 0),
        (655, 82, 'SELECT c.customer_id FROM customers c INNER JOIN orders o ON c.customer_id = o.customer_id GROUP BY c.customer_id ORDER BY COUNT(o.order_id) DESC;', 0),
        (656, 82, 'SELECT customer_id FROM orders GROUP BY customer_id HAVING SUM(order_amount) > (SELECT AVG(order_amount) FROM orders);', 0),
        (658, 83, 'SELECT employee_id FROM employees WHERE salary > (SELECT MAX(salary) FROM employees);', 0),
        (659, 83, 'SELECT e.employee_id FROM employees e JOIN departments d ON e.department_id = d.department_id WHERE e.salary > d.average_salary;', 0),
        (660, 83, 'SELECT employee_id, salary FROM employees WHERE salary > (SELECT MIN(salary) FROM employees);', 0),
        (661, 83, 'SELECT employee_id, salary FROM employees WHERE salary = (SELECT MAX(salary) FROM employees);', 0),
        (662, 83, 'SELECT employee_id, salary FROM employees WHERE salary > (SELECT salary FROM employees ORDER BY salary DESC LIMIT 1);', 0),
        (663, 83, 'SELECT employee_id, name, salary FROM employees WHERE salary >= (SELECT AVG(salary) FROM employees WHERE department_id = employees.department_id);', 1),
        (664, 83, 'SELECT employee_id, name, salary FROM employees WHERE salary IN (SELECT MAX(salary) FROM employees GROUP BY department_id);', 0),
        (666, 84, 'SELECT product_id FROM orders WHERE order_date > NOW() - INTERVAL 3 MONTH GROUP BY product_id;', 0),
        (667, 84, 'SELECT product_id FROM orders GROUP BY product_id HAVING SUM(quantity) = (SELECT MAX(SUM(quantity)) FROM orders);', 0),
        (668, 84, 'SELECT product_id, SUM(quantity) FROM orders WHERE order_date BETWEEN DATE_SUB(NOW(), INTERVAL 3 MONTH) AND NOW() GROUP BY product_id ORDER BY SUM(quantity) DESC LIMIT 1;', 1),
        (669, 84, 'SELECT product_id FROM orders WHERE order_date > NOW() - INTERVAL 6 MONTH;', 0),
        (670, 84, 'SELECT product_id FROM orders GROUP BY product_id HAVING MAX(quantity) > 100;', 0),
        (671, 84, 'SELECT product_id FROM orders WHERE SUM(quantity) > 50 GROUP BY product_id;', 0),
        (672, 84, 'SELECT product_id, COUNT(*) FROM orders WHERE order_date BETWEEN DATE_SUB(NOW(), INTERVAL 3 MONTH) AND NOW() GROUP BY product_id ORDER BY COUNT(*) DESC LIMIT 1;', 0),
        (674, 85, 'SELECT customer_id, order_amount, "VIP" FROM orders WHERE order_amount > 1000;', 0),
        (675, 85, 'SELECT customer_id FROM orders GROUP BY customer_id HAVING SUM(order_amount) >= 500;', 0),
        (676, 85, 'SELECT customer_id, CASE WHEN SUM(order_amount) > (SELECT AVG(order_amount) FROM orders) THEN "HIGH SPENDER" ELSE "LOW SPENDER" END AS category FROM orders GROUP BY customer_id;', 1),
        (677, 85, 'SELECT customer_id, order_amount FROM orders WHERE order_amount BETWEEN 500 AND 1000;', 0),
        (678, 85, 'SELECT customer_id, "VIP" FROM orders WHERE order_amount > 500;', 0),
        (679, 85, 'SELECT customer_id FROM orders GROUP BY customer_id HAVING SUM(order_amount) >= (SELECT AVG(order_amount) FROM orders);', 0),
        (680, 85, 'SELECT customer_id, COUNT(*) FROM orders WHERE order_amount > 500 GROUP BY customer_id;', 0),
        (682, 86, 'SELECT category_id, SUM(price * quantity) FROM sales GROUP BY category_id;', 0),
        (683, 86, 'SELECT category_id, SUM(price * quantity), COUNT(*) FROM sales GROUP BY category_id;', 0),
        (684, 86, 'SELECT category_id, SUM(price * quantity) OVER (PARTITION BY category_id) FROM sales;', 0),
        (685, 86, 'SELECT category_id, SUM(price * quantity) FROM sales GROUP BY category_id WITH ROLLUP;', 0),
        (686, 86, 'SELECT category_id, total_sales FROM (SELECT category_id, SUM(price * quantity) AS total_sales FROM sales GROUP BY category_id) AS subquery;', 0),
        (687, 86, 'SELECT category_id, SUM(price * quantity) AS total_sales FROM sales WHERE category_id IS NOT NULL GROUP BY category_id UNION ALL SELECT NULL, SUM(price * quantity) FROM sales;', 1),
        (688, 86, 'SELECT category_id, SUM(price * quantity) FROM sales WHERE category_id IS NOT NULL GROUP BY category_id HAVING SUM(price * quantity) > 10000;', 0),
        (689, 87, 'SELECT customer_id, name FROM customers WHERE NOT EXISTS (SELECT 1 FROM orders WHERE customers.customer_id = orders.customer_id);', 1),
        (692, 87, 'SELECT c.customer_id FROM customers c INNER JOIN orders o ON c.customer_id = o.customer_id WHERE c.customer_id NOT IN (SELECT DISTINCT customer_id FROM orders);', 0),
        (693, 87, 'SELECT customer_id FROM customers WHERE customer_id IN (SELECT customer_id FROM orders WHERE COUNT(order_id) = 0);', 0),
        (694, 87, 'SELECT c.customer_id FROM customers c FULL OUTER JOIN orders o ON c.customer_id = o.customer_id WHERE o.customer_id IS NULL;', 0),
        (695, 87, 'SELECT DISTINCT customer_id FROM customers WHERE NOT EXISTS (SELECT 1 FROM orders WHERE orders.customer_id = customers.customer_id AND order_date > NOW() - INTERVAL 1 YEAR);', 0),
        (696, 87, 'SELECT customer_id, COUNT(*) FROM customers WHERE NOT EXISTS (SELECT 1 FROM orders WHERE customers.customer_id = orders.customer_id) GROUP BY customer_id;', 0),
        (697, 88, 'SELECT employee_id, name, salary, RANK() OVER (PARTITION BY department_id ORDER BY salary DESC) AS salary_rank FROM employees;', 1),
        (698, 88, 'SELECT employee_id, name, salary FROM employees WHERE salary = (SELECT MAX(salary) FROM employees GROUP BY department_id);', 0),
        (699, 88, 'SELECT employee_id, name, salary FROM employees ORDER BY salary DESC LIMIT 5;', 0),
        (700, 88, 'SELECT employee_id, name, salary, RANK() OVER (ORDER BY salary DESC) FROM employees;', 0),
        (702, 88, 'SELECT employee_id, name, salary FROM employees WHERE salary >= (SELECT AVG(salary) FROM employees GROUP BY department_id);', 0),
        (703, 88, 'SELECT employee_id, name, salary FROM employees WHERE salary >= ALL (SELECT salary FROM employees WHERE department_id = employees.department_id);', 0),
        (704, 88, 'SELECT employee_id, name, salary, ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC) FROM employees;', 0),
        (705, 89, 'SELECT product_id, name FROM products WHERE NOT EXISTS (SELECT 1 FROM orders WHERE products.product_id = orders.product_id);', 1),
        (708, 89, 'SELECT product_id FROM orders WHERE product_id NOT IN (SELECT DISTINCT product_id FROM orders);', 0),
        (709, 89, 'SELECT product_id FROM products WHERE NOT EXISTS (SELECT product_id FROM orders WHERE order_date > NOW() - INTERVAL 1 YEAR);', 0),
        (710, 89, 'SELECT product_id FROM products WHERE COUNT(*) = 0;', 0),
        (711, 89, 'SELECT DISTINCT product_id FROM products WHERE NOT EXISTS (SELECT 1 FROM orders WHERE orders.product_id = products.product_id AND order_date > NOW() - INTERVAL 1 YEAR);', 0),
        (712, 89, 'SELECT product_id FROM orders WHERE COUNT(order_id) = 0;', 0),
        (713, 90, 'SELECT customer_id, YEAR(order_date) AS year, MONTH(order_date) AS month, SUM(amount) AS total_spent FROM orders GROUP BY customer_id, GROUPING SETS ((YEAR(order_date), MONTH(order_date)), (YEAR(order_date)), ());', 1),
        (714, 90, 'SELECT customer_id, order_date, SUM(amount) FROM orders GROUP BY customer_id, order_date;', 0),
        (716, 90, 'SELECT customer_id, YEAR(order_date) AS year, SUM(amount) FROM orders GROUP BY customer_id, YEAR(order_date);', 0),
        (717, 90, 'SELECT customer_id, SUM(amount) FROM orders GROUP BY customer_id WITH ROLLUP;', 0),
        (718, 90, 'SELECT customer_id, order_date, SUM(amount) AS total_spent FROM orders GROUP BY customer_id, order_date ORDER BY customer_id;', 0),
        (719, 90, 'SELECT customer_id, YEAR(order_date), MONTH(order_date), SUM(amount) FROM orders WHERE amount > 5000 GROUP BY customer_id, YEAR(order_date), MONTH(order_date);', 0),
        (720, 90, 'SELECT customer_id, order_date, SUM(amount) FROM orders GROUP BY customer_id, YEAR(order_date), MONTH(order_date), order_date;', 0);